### PR TITLE
Fix LincombOperator.assemble in 0.5.x

### LINKED ISSUE #794: NumpyGenericOperator lincomb apply_inverse infinite recursion in 0.5.x
The following raises `RecursionError` on 0.5.x.
```python
import numpy as np
from pymor.operators.numpy import NumpyMatrixOperator, NumpyGenericOperator

n = 2
I1 = NumpyMatrixOperator(np.eye(n))
I2 = NumpyGenericOperator(lambda x: x, dim_source=n, dim_range=n)
v = I1.source.from_numpy(np.ones(n))

(I1 + I2).apply_inverse(v)
```

On master, `jacobian` method raises `NotImplementedError`.

Should the recursion error be fixed in 0.5.x?

### PR DESCRIPTION
**Pull request by pmli**
Fixes #794 

It seems the issue was in comparing a list with a tuple in

https://github.com/pymor/pymor/blob/9a70dc739187c3cffce2d017a84e8c2b2e8b62f2/src/pymor/operators/constructions.py#L136

### CODE REVIEW

**Comment by pmli** [comment]
Agreed.
I've added the test and backported `IdentityOperator` lincomb tests.

**Comment by pmli** [comment]
`centos_7` tests are the only ones failing.

**Comment by pmli** [comment]
@renefritze Any ideas why the tests failed?

**Comment by renefritze** [comment]
> @renefritze Any ideas why the tests failed?

Not really. Requiring an older version (2.3 maybe, since 2.4.4 gets installed in the log) of pyparsing in our dependencies might be a workaround though.

**Pull request merged**
