### PR TITLE
meshio4

### LINKED ISSUE #1092: meshio 4
I notice that meshio #793 is pinned at [3.3.1](https://github.com/nschloe/meshio/releases/tag/3.3.1)

https://github.com/pymor/pymor/blob/4fc3893a3746da584aa006db24f9ec210f366cba/dependencies.py#L34

I was looking writing bindings for [scikit-fem](https://github.com/kinnala/scikit-fem) but it uses the [latest](https://github.com/nschloe/meshio/releases/latest), currently [4.2.0](https://github.com/nschloe/meshio/releases/tag/v4.2.0) so I can't easily install scikit-fem and pyMOR in the same env.   There were a number of backwardly incompatible changes introduced into meshio 4, so I don't think scikit-fem will work with meshio 3.3.1.

Would there be interest in a pull request to update pyMOR to meshio 4.2.0?  Are there particular reasons for sticking at 3.3.1?

### PR DESCRIPTION
**Pull request by gdmcbain**
Fixes #1092. 

(This is mostly to see how big a change is required and to make use of the continuous integration to test against more versions of Python etc. than I have installed.)

### CODE REVIEW

**Comment by sdrave** [comment]
@renefritze, somehow this PR did not trigger a CI build. Maybe related to the recent Gitlab update?

**Comment by renefritze** [comment]
I hope the general CI issue is fixed now.

CI checks if `dependencies.py` and the `requirements*` files match. If you execute `./dependencies.py` (or just `make`) and commit the update, then CI should continue.

**Comment by renefritze** [comment]
Sorry I didn't think of that right away, but I'll have to update the CI images so that the pypi mirror serves the newer meshio.

**Comment by renefritze** [comment]
Sorry for the spam, @gdmcbain, the bot isn't quite doing what it's supposed to and needs some reprogramming still. 
Meanwhile, docker images are updating [here](https://github.com/pymor/docker-all/pull/23).

**Review by renefritze — APPROVED** [review]

**Comment by renefritze** [comment]
There's now an actual pytest error happening: https://zivgitlab.uni-muenster.de/pymor/pymor/-/jobs/423244#L966

**Comment by gdmcbain** [comment]
> There's now an actual pytest error happening: https://zivgitlab.uni-muenster.de/pymor/pymor/-/jobs/423244#L966

Yes.  I see that it's in 

https://github.com/nschloe/meshio/blob/d467cb8a49e218b7bee899f59def3c3f898b3133/meshio/gmsh/_gmsh41.py#L117

I'm not getting the error here though with
```shell
python src/pymordemos/elliptic_unstructured.py 6 16 1e-1
``` 

Perhaps as without an explicit installation of Gmsh, pyMOR's picking up `/usr/bin/gmsh` which is 4.4.1 for Ubuntu 20.04.1 LTS.  If (as usual) I do
```shell
pip install gmsh-sdk
```
I get 4.6.0.

At https://zivgitlab.uni-muenster.de/pymor/pymor/-/jobs/423244#L981, it looks like Gmsh 4.1.3.  This was a shortlived buggy version of Gmsh, as noted in nschloe/meshio#797:

> That's a bug indeed, but mind you not many people take interest in this particular version of gmsh. It uses an "intermediate" format that was fixed on version after. You might want to upgrade.

Any chance of upgrading from Gmsh 4.1.3?

**Comment by sdrave** [comment]
> I get 4.6.0, and no error with that either.
> 
> At https://zivgitlab.uni-muenster.de/pymor/pymor/-/jobs/423244#L981, it looks like Gmsh 4.1.3. This was a shortlived buggy version of Gmsh, as noted in [nschloe/meshio#797](https://github.com/nschloe/meshio/issues/797):
> 
> > That's a bug indeed, but mind you not many people take interest in this particular version of gmsh. It uses an "intermediate" format that was fixed on version after. You might want to upgrade.
> 
> Any chance of upgrading from Gmsh 4.1.3?

Debian stable, on which our CI images are based if I remember correctly, has `4.1.5+really4.1.3+ds1-1`. On my Debian machine I get the same error locally. However, I would be fine with adding `gmsh` to our `pymor[full]` requirements (`gmsh-sdk` is deprecated). It has wheels for all relevant platforms.

**Comment by renefritze** [comment]
I agree, adding the python package that gets us the right gmsh would be a better solution than to get a newer gmsh binary into our debian stable based images. 

I'll update the images again to make `gmsh` available.

**Comment by renefritze** [comment]
I realized I missed some stuff in my previous commit @gdmcbain, so I've added a fixup commit which we should squash before the merge.

**Comment by renefritze** [comment]
It seems we're now having trouble calling the gmsh binary/script installed from the `gmsh` python package. I can look into that after the pyMOR course is over.

**Comment by renefritze** [comment]
The CI images needed some more Xorg packages that had been installed as a gmsh apt package before. It'll take a bit to get those updates out and then I'll restart the gitlab pipelines.

**Comment by renefritze** [comment]
Tests are looking good now. If there's nothing else @gdmcbain @pymor/pymor-devs , I'll merge this in a day.

**Comment by gdmcbain** [comment]
No, that looks good.  Thanks very much for following this through; there were a few more things required than I had envisaged.

**Comment by renefritze** [comment]
> No, that looks good. 

Great. This is now on track to merge. Thank you again for your work, @gdmcbain !

**Pull request merged**
