### PR TITLE
Python 3

### PR DESCRIPTION
**Pull request by renemilk**

### CODE REVIEW

**Comment by sdrave** [comment]
Ok, so I believe we have finally fixed all obvious issues with the python3 branch. If no one objects, I will merge to master on Friday. Any objections, @renemilk, @ftalbrecht, @andreasbuhr, @pmli?

**Comment by andreasbuhr** [comment]
Great! :-)

**Comment by pmli** [comment]
No objections :)

**Comment by ftalbrecht** [comment]
None from my side.

**Pull request merged**
