### PR TITLE
Improve rendering of tutorial notebooks

### LINKED ISSUE #1878: Jupyter breaking with some package configs
`jupyter_server>=2` does have issues with `jupytext` (or actually the other way around. The result is that the auth cookie somehow gets mangled, with no kernel interaction being possible afterwards. 
To prevent this from occurring I'll add an explicit pin on `jupyter_server<2` in our deps for now. That needs to checked after https://github.com/mwouts/jupytext/pull/1021 is completed.

### PR DESCRIPTION
**Pull request by sdrave**
myst-nb just copy-pastes the myst markdown into the generated jupyter notebooks. This pr significantly improves the appearance of the notebooks by:

- updating pyMOR's jupyter requirements s.t. the ci images use jupyterlab instead of the notebook interface on binder,
- including `jupyterlab-myst` into our ci images, which adds myst rendering support to jupyterlab
- postprocessing the generated notebooks with some regular expressions to remove sphinx directives, which are not properly rendered by the myst parser in jupyterlab.

Fixes #1878.

### CODE REVIEW

**Comment by sdrave** [comment]
@pymor/main, please take a look. I'd like to have this merged before the school so that working with these notebooks is actually a bearable experience ..

**Comment by lbalicki** [comment]
Can I somehow take a look at the tutorial notebooks on binder such that the ci changes from this PR are applied?

**Comment by sdrave** [comment]
> Can I somehow take a look at the tutorial notebooks on binder such that the ci changes from this PR are applied?

https://docs.pymor.org/notebooks-fix-myst/index.html and use one of the binder links. If the link is dead, docs need to be deployed again by rerunning the docs deploy job on gitlab.

**Comment by lbalicki** [comment]
Looks very nice and is very fast after the first start-up. Judging from the logs everything seems to work as expected. There are some minor cosmetic things that need to be adjusted in e.g. the BT tutorial (there are scroll bars on the aligned equations). But I think this can be part of a separate PR. Also, this PR supersedes #2174 , right?

**Review by lbalicki — APPROVED** [review]

**Comment by sdrave** [comment]
> But I think this can be part of a separate PR. Also, this PR supersedes https://github.com/pymor/pymor/pull/2174 , right?

No this PR is built on #2174. This PR only contains the things mentioned above. I guess I'll merge both PRs now ..

**Pull request merged**
