### PR TITLE
Support different colormaps in GLPatchWidget

### PR DESCRIPTION
**Pull request by sdrave**
This is some work I have done a while ago. We still need to wire everything up ...

### CODE REVIEW

**Comment by sdrave** [comment]
I have now finished the colormap support and defaulted the new colormap to viridis. Please, everyone, have a look if the new code works correctly on your machine.

**Comment by ftalbrecht** [comment]
`thermalblock_gui.py` seems to work as expected under arch linux. Anything else I should test?

**Comment by sdrave** [comment]
Since `thermalblock_gui.py` is special case, better also have a look at `thermalbock.py` and `burgers.py`.

**Comment by ftalbrecht** [comment]
`./thermalblock.py --plot-err --plot-solutions --plot-error-sequence ...` and `./burgers.py ...` work for me.

**Comment by renemilk** [comment]
All three look good for me

**Comment by pmli** [comment]
(If you're happy, I'm happy.)

**Pull request merged**
