### PR TITLE
Remove 'if config.HAVE_...' checks in modules that require optional dependencies

### PR DESCRIPTION
**Pull request by sdrave**
This pr adds ~`require_dependency` to `pymor.core.config`~ a `require` method to `pymor.core.config.config`, which will raise an `DependencyMissing` error when the provided config item is not available. I refactored all relevant modules to use this mechanism instead of the current `if config.HAVE_FOO` checks, which lead to unnecessary indents and leads to the surprising behavior that an imported module is empty. As a consequence, importing e.g. `pymor.bindings.fenics` will raise an error, when fenics is unavailable. To avoid an exception one, thus, has to check first for fenics availability and then conditionally import the bindings. In practice this should be only necessary in very few places.

Also see discussion in #1343.

### CODE REVIEW

**Comment by sdrave** [comment]
It just occurred to me that `config.require('QT')` might be nicer than `require_dependency('QT')`?

**Review by renefritze — CHANGES_REQUESTED** [review]
Would it be a good idea to add a test with a `require` on an unsatisfiable dependency to check the new functionality?

**Comment by sdrave** [comment]
It's `config.require()` now.

> Would it be a good idea to add a test with a `require` on an unsatisfiable dependency to check the new functionality?

I have added two trivial tests. Testing for an actually missing dependency would require having a missing dependency. I don't think it's worth the trouble to create a setup for this.

**Comment by renefritze** [comment]
> It's `config.require()` now.
> 
> > Would it be a good idea to add a test with a `require` on an unsatisfiable dependency to check the new functionality?
> 
> I have added two trivial tests. 

Great.

> Testing for an actually missing dependency would require having a missing dependency. I don't think it's worth the trouble to create a setup for this.

Something like this should do and not be a lot of hassle I think:
```
def test_require_fail_foo(monkeypatch):
    monkeypatch.setitem(config._PACKAGES, 'THISISNOTAPACKAGENAMETHATEXISTS', lambda : False)
    with pytest.raises(DependencyMissing):
        config.require('THISISNOTAPACKAGENAMETHATEXISTS')
```

**Comment by sdrave** [comment]
> > Testing for an actually missing dependency would require having a missing dependency. I don't think it's worth the trouble to create a setup for this.
> 
> Something like this should do and not be a lot of hassle I think:
> 
> ```
> def test_require_fail_foo(monkeypatch):
>     monkeypatch.setitem(config._PACKAGES, 'THISISNOTAPACKAGENAMETHATEXISTS', lambda : False)
>     with pytest.raises(DependencyMissing):
>         config.require('THISISNOTAPACKAGENAMETHATEXISTS')
> ```

Thanks, I've added the test.

**Review by renefritze — APPROVED** [review]

**Comment by sdrave** [comment]
@renefritze, the strange `WARNING: Unknown type: placeholder` messages were apparently due to double imports of `pymor.core.config.config`, which, BTW, weren't caught by flake8.

**Comment by renefritze** [comment]
> @renefritze, the strange `WARNING: Unknown type: placeholder` messages were apparently due to double imports of `pymor.core.config.config`, which, BTW, weren't caught by flake8.

Yep, looks like there's simply [no check](https://flake8.pycqa.org/en/latest/user/error-codes.html) for this in base flake8. It's not F401. since it's used below. And it's not F811 I guess since the definition does not change?

I think this would need a flake8 plugin then? This could be a good base: https://github.com/atollk/flake8-import-restrictions/blob/master/flake8_import_restrictions/checker.py

**Comment by sdrave** [comment]
I *do* get F811 on double import. But only for double imports at the top of the module. If there is some code inbetween, e.g. `config.require('foo')`, then everything below that code is ignored. (Probably because it would raise E402, which is now disabled.

**Comment by renefritze** [comment]
I see. So basically a plugin would need the ignoring E402 baked in and still throw F811 then.

**Comment by sdrave** [comment]
Something like that. I wouldn't care as long as we don't encounter this issue regularly.

**Comment by renefritze** [comment]
Agreed.

**Pull request merged**
