### PR TITLE
[core.logger] allow to enable simultaneous file logging

### PR DESCRIPTION
**Pull request by ftalbrecht**
See the commit messages.

### CODE REVIEW

**Comment by ftalbrecht** [comment]
Given that #81 is decided (but not fully implemented yet), should I prepare this one for 0.3.x?

**Comment by sdrave** [comment]
How are you planning to implement it?

**Comment by ftalbrecht** [comment]
As you suggested already: fix the bug, use `@defaults('filename')`.

**Comment by sdrave** [comment]
Ok.

**Comment by ftalbrecht** [comment]
I implemented this in 16f3873a46d42c977e57d82122fa34d9adcd9013. Unfortunately I also pushed this into the wrong repository, it is now already in the 0.3.x branch of the main repository. If this is ok, please close (not merge!) this pr, @sdrave. If not, revert it and I will do it properly. We then have to pick those commits to master also, if they should stay.

**Comment by sdrave** [comment]
Also applied 16f3873 to master, so closing this pull request.

**Pull request closed without merging**
