### PR TITLE
[sys-mor] Biorthogonalization, Sylvester equations, TSIA

### PR DESCRIPTION
**Pull request by pmli**
Added:
- biorthogonal Gram-Schmidt process in `algorithms.gram_schmidt`,
- sparse-dense Sylvester equation solver in `algorithms.sylvester`,
- TSIA (Two Sided Iteration Algorithm) in `reductors.lti`,
- yet another complex numbers bug fix.

### CODE REVIEW

**Comment by sdrave** [comment]
Looks nice! You might want to open a separate pull request for `gram_schmidt_biorth`, since we could merge this into master right away.

**Comment by pmli** [comment]
Can we merge this?

**Comment by sdrave** [comment]
Since we had some changes in the sys-mor branch, I would like to rebase on sys-mor and force push to get a cleaner diff of the changes. Is that ok?

**Comment by pmli** [comment]
Yeah, sounds good.

**Comment by sdrave** [comment]
Done. I fixed some left-overs from the apply_adjoint -> apply_transpose transition. LGTM now, merge when you are happy with it.

**Comment by pmli** [comment]
Thanks!

**Pull request merged**
