### PR TITLE
Restructuring of grid classes

### LINKED ISSUE #987: Move defaultimpl.py into interfaces.py in discretizers/builtin/grids?
It seems that `ConformalTopologicalGridDefaultImplementations`/`ReferenceElementDefaultImplementations`/`AffineGridDefaultImplementations` could be merged into `ConformalTopologicalGrid`/`ReferenceElement`/`AffineGrid` without issues.

### PR DESCRIPTION
**Pull request by pmli**
Closes #987

So far, I only moved the code. Further improvements might be possible.

_Update_: This PR:

- merges `ConformalTopologicalGridDefaultImplementations`, `ReferenceElementDefaultImplementations`, `AffineGridDefaultImplementations` into `ConformalTopologicalGrid`, `ReferenceElement`, `AffineGrid`,
- merges `ConformalTopologicalGrid` into `AffineGrid`,
- renames `AffineGrid` and `AffineGridWithOrthogonalCenters` to `Grid` and `GridWithOrthogonalCenters`.

### CODE REVIEW

**Comment by pmli** [comment]
It looks like hypothesis found a failing example for `test_axpy`.

**Comment by pmli** [comment]
I was wondering about having `ConformalTopologicalGrid` since it's only used as a superclass to `AffineGrid`, but I guess there is a reason to keep it.

**Comment by renefritze** [comment]
> but I guess there is a reason to keep it.

I'd also say it's superfluous.

**Comment by sdrave** [comment]
> > but I guess there is a reason to keep it.
> 
> I'd also say it's superfluous.

I agree that `ConformalTopologicalGrid` can be merged into `AffineGrid`. While we are at it, one might also rename `AffineGrid` to just `Grid`. I don't think that we will ever have a grid with non-affine reference maps in `discretizers.builtin`.

**Comment by pmli** [comment]
@sdrave Just to make sure, by approving this PR, you mean it can be merged and that the merging of `ConformalTopologicalGrid` and `AffineGrid` into `Grid` can be done in a new PR?

**Comment by sdrave** [comment]
> @sdrave Just to make sure, by approving this PR, you mean it can be merged and that the merging of `ConformalTopologicalGrid` and `AffineGrid` into `Grid` can be done in a new PR?

Can be done in the same PR. A separate PR is fine as well ..

**Pull request merged**
