### PR TITLE
Py3js-based Jupyter Visualization

### PR DESCRIPTION
**Pull request by renefritze**
This supersedes #629 

~~There's currently a bug that duplicates the log output accordion wrapper, please ignore.~~

referencing #647, the implementation in this PR does:

Minimal:
 - [x] 2D only view of 2D (point+cell, scalar) data 
 - [x] time series support
 - [x] notebook embeddable (visualization is usable w/o executing the cell after opening the notebook)
 - [x] colorbar 
 - [x] "good" default color map
 - [x] "play" controls for time series/multi param arrays

Nice to have: 
 - [ ] 3D data with cut plane/thresholding support
 - [ ] vector valued functions
 - [ ] static representation (nbviewer)
 - [ ] warp-by-scalar elevation plot like visualization 
 - [ ] live appending of data
 - [x] selectable color maps
 - [x] multiple parallel data views

Try it: [Binder](https://mybinder.org/v2/gh/pymor/pymor/py3js?filepath=elliptic.ipynb)

### CODE REVIEW

**Comment by renefritze** [comment]
Could we clarify what "live appending of data" means? 
Should the visualization auto-magically update when vectors, for example from an ongoing instationary solve, get appended to a visualized VectorArray?

**Comment by renefritze** [comment]
Notebook embedding now works for non timeseries data.

**Comment by sdrave** [comment]
@renefritze, I think there are still too many glitches to have this as a standard in 2019.2. I would vote for adding a `default` to switch between WebGL- and matplotlib-based visualization and set it to `'matplotlib'`. For 2020.1 we should be able to change it to `'webgl'`

**Comment by renefritze** [comment]
I'd rather set the default to webgl in master and only to matplotlib in the release branch.

**Comment by sdrave** [comment]
Agreed.

**Comment by renefritze** [comment]
From my POV this can be merged into master to get broader usage and testing.

**Pull request merged**
