### PR TITLE
add NumFOCUS badge

### PR DESCRIPTION
**Pull request by artpelling**
I noticed that our affiliation is not mentioned anywhere, so I made a small badge.

### CODE REVIEW

**Review by pmli — APPROVED** [review]

**Comment by artpelling** [comment]
> Putting the NumFOCUS text next to the logo might be problematic, as the proper logo would have the brackets inside the 'O'. So I'd suggest to ask them first if using the badge is fine. Also, they might be interested in offering an official badge that other projects might use as well.

It seems like they have the normal logo and a small logo without text. I removed the logo for now to be sure. But for non-software, its okay to use their logo if it links to the project site (which it does) according to the guidelines.
The badge at https://github.com/weecology/retriever seems way worse, it doesn't look like an official one.

I guess it wouldn't hurt to ask for permission to be absolutely sure.

**Comment by pmli** [comment]
I suggest using

[Affiliated with NumFOCUS](https://numfocus.org/sponsored-projects/affiliated-projects)

(as [AiiDA](https://github.com/aiidateam/aiida-core)).

**Comment by HenKlei** [comment]
Who is going to take care of this @artpelling, @pmli?

**Review by sdrave — APPROVED** [review]

**Comment by sdrave** [comment]
Thanks, @artpelling!

**Pull request merged**
