### PR TITLE
[scipy] convert to CSC before splu call

### PR DESCRIPTION
**Pull request by pmli**
Fix for #386.

### CODE REVIEW

**Comment by sdrave** [comment]
LGTM

**Comment by pmli** [comment]
Ok, I will wait for the checks to complete.

**Comment by pmli** [comment]
@sdrave Well, some of the checks passed...

**Comment by sdrave** [comment]
Sorry, accidentally broke master yesterday. I have rebased your commit on fixed master. Hopefully, everything should be green soon.

**Pull request merged**
