### PR TITLE
ci mpi debug

### PR DESCRIPTION
**Pull request by renefritze**
Just a bunch of ideas from the dev meeting I could 
quickly send to the gitlab to try out.

@sdrave feel free to push into this branch if you have more ideas to try out

### CODE REVIEW

**Comment by renefritze** [comment]
So I found a bunch of failures :tada: 
https://zivgitlab.uni-muenster.de/pymor/pymor/-/jobs/848585
https://zivgitlab.uni-muenster.de/pymor/pymor/-/jobs/848650
https://zivgitlab.uni-muenster.de/pymor/pymor/-/jobs/848663
https://zivgitlab.uni-muenster.de/pymor/pymor/-/jobs/848598
https://zivgitlab.uni-muenster.de/pymor/pymor/-/jobs/848679

and then I broke the exit check logic.

**Comment by renefritze** [comment]
More data:
Runs also fail on other runners than the default one. 

I find it at least suspicious that in the unbuffered mode this appears right at the [timeout point](https://zivgitlab.uni-muenster.de/pymor/pymor/-/jobs/850120#L2900)
```
2900QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-pymor'
2901Failed to create  for shader cache (No such file or directory)---disabling.
```

**Comment by renefritze** [comment]
Still hangs https://zivgitlab.uni-muenster.de/pymor/pymor/-/jobs/861191#L3654 even w/o plots

**Comment by sdrave** [comment]
Now that I disabled all plotting in the `thermalblock_simple` demo, the job hangs in another demo with the same message appearing before. Seems very likely that the issue is related to Qt/matplotlib.

**Comment by sdrave** [comment]
> Still hangs https://zivgitlab.uni-muenster.de/pymor/pymor/-/jobs/861191#L3654 even w/o plots

Somehow I didn't see this before posting the comment. As I said, it now hangs in a different demo. I will disable the fenics visualizer completely as a next step.

**Pull request closed without merging**
