### PR TITLE
Fix "neighbor" typo

### PR DESCRIPTION
**Pull request by pmli**
- renames methods with "neighbour"

### CODE REVIEW

**Review by sdrave — CHANGES_REQUESTED** [review]
This breaks public API of grids. I don't think eliminating British English is worth the effort. If it is, we should go through a deprecation cycle at least.

**Comment by pmli** [comment]
I'm not sure if it's worth the effort (that's why I made it a draft PR). If this API is not used so often, maybe it's ok to rename it.

**Comment by sdrave** [comment]
@pmli, how should we proceed? I'm ok with renaming if we properly deprecate the existing method in the upcoming release. I'm also fine with closing the pr and keeping the current situation ..

**Comment by pmli** [comment]
I would be for deprecating.

**Review by sdrave — APPROVED** [review]

**Pull request merged**
