### PR TITLE
Add pyMOR logo

### PR DESCRIPTION
**Pull request by sdrave**
@pymor/pymor-devs, any final comments?

### CODE REVIEW

**Comment by renefritze** [comment]
> @pymor/pymor-devs, any final comments?

No

**Comment by sdrave** [comment]
@renefritze, any idea what's going on with ci?

**Comment by HenKlei** [comment]
I think we should remember to put the logo on the pyMOR website and maybe also in the documentation.

**Comment by renefritze** [comment]
> @renefritze, any idea what's going on with ci?

Yes. You can read all about it in [the log](https://zivgitlab.uni-muenster.de/pymor/pymor/-/jobs/410761#L2179) :wink:

**Comment by sdrave** [comment]
> > @renefritze, any idea what's going on with ci?
> 
> Yes. You can read all about it in [the log](https://zivgitlab.uni-muenster.de/pymor/pymor/-/jobs/410761#L2179) wink

Hmpf. I keep making this error and not even finding it ..

I think we should not add the logo to the package. So I just pushed a commit to ignore the 'logo' dir.

**Comment by renefritze** [comment]
> I think we should not add the logo to the package. 

I agree.

**Comment by renefritze** [comment]
> I think we should remember to put the logo on the pyMOR website and maybe also in the documentation.

Do you want to try your hand at that? The current pymor.org is served from the gh-pages branch in this repo, docs ofc via sphinx.

**Comment by HenKlei** [comment]
> Do you want to try your hand at that, @HenKlei? The current pymor.org is served from the gh-pages branch in this repo, docs ofc via sphinx.

I will give it a try tomorrow.

**Comment by sdrave** [comment]
I think we should also include the logo in `README.md` as many people will only look at the github repo.

**Pull request merged**
