### PR TITLE
Support Python 3.12

### PR DESCRIPTION
**Pull request by sdrave**
This PR adds official support for Python 3.12 and updates ci-current and conda CI environments to this version.

### CODE REVIEW

**Comment by sdrave** [comment]
@ftschindler, there are no dune-xt/dune-gdt wheels for 3.12. Is there a timeline?

**Comment by sdrave** [comment]
> @ftschindler, there are no dune-xt/dune-gdt wheels for 3.12. Is there a timeline?

@ftschindler, any updates?

**Comment by ftschindler** [comment]
> > @ftschindler, there are no dune-xt/dune-gdt wheels for 3.12. Is there a timeline?
> 
> @ftschindler, any updates?

Did not see that ping a month ago, sry. Will look into it ...

**Comment by sdrave** [comment]
> > > @ftschindler, there are no dune-xt/dune-gdt wheels for 3.12. Is there a timeline?
> > 
> > 
> > @ftschindler, any updates?
> 
> Did not see that ping a month ago, sry. Will look into it ...

@ftschindler, what's the status? As soft freeze is approaching, I'll have to merge this soonish.

**Comment by ftschindler** [comment]
> > > > @ftschindler, there are no dune-xt/dune-gdt wheels for 3.12. Is there a timeline?
> > > 
> > > 
> > > @ftschindler, any updates?
> > 
> > 
> > Did not see that ping a month ago, sry. Will look into it ...
> 
> @ftschindler, what's the status? As soft freeze is approaching, I'll have to merge this soonish.

I'm looking into it, can give you more info in a day or two. What's the time frame I have?

**Comment by sdrave** [comment]
@ftschindler, I'd say this should be merged in about two weeks.

**Comment by ftschindler** [comment]
> @ftschindler, I'd say this should be merged in about two weeks.

thx for the note. Making some progress, let's see :/

**Comment by sdrave** [comment]
@ftschindler, I will merge this now. Please let me know when updated gdt wheels are available.

**Pull request merged**
