### PR TITLE
[newton] fixed bugs with residual being exactly 0

### PR DESCRIPTION
**Pull request by HenKlei**
Addresses #927.

This merge request fixes a bug that occurred when the residual in the Newton algorithm becomes exactly 0.

### CODE REVIEW

**Comment by HenKlei** [comment]
Yes, I think that's better. That was also my first idea. Then we can remove the first `if`-condition, I think. As far as I can see, the second one is required nevertheless.

**Comment by sdrave** [comment]
> As far as I can see, the second one is required nevertheless.

Don't think so. If `error_squence[-1]` is not the current but the last error. And if it was zero, then we would have aborted the loop?!

**Comment by HenKlei** [comment]
> Don't think so. If `error_squence[-1]` is not the current but the last error. And if it was zero, then we would have aborted the loop?!

Yeah, you're absolutely right. Having 0 as default value for atol and rtol, that should work.

**Comment by HenKlei** [comment]
I think this is the simplest solution now. The test is also working as expected. Thus, merging is fine with me.
@sdrave Do you have any objections or further comments?

**Comment by sdrave** [comment]
Looks good to me! I will merge as is.

**Pull request merged**
