### PR TITLE
Update mailmap before the 2020.2 release

### PR DESCRIPTION
**Pull request by renefritze**

### CODE REVIEW

**Comment by renefritze** [comment]
Looks like we can assign groups as reviewers too btw. At least from the gh CLI I could.

**Review by pmli — COMMENTED** [review]
You might want to add a line for `<47802+renefritze@users.noreply.github.com>`.

Also, it would be nice to keep the file sorted...

**Comment by renefritze** [comment]
> You might want to add a line for `<47802+renefritze@users.noreply.github.com>`.
> Also, it would be nice to keep the file sorted...

Right. Will do both.

Btw, do you remember what the single `name email` lines' functions are? I did not find that in the spec.

**Comment by pmli** [comment]
> Btw, do you remember what the single `name email` lines' functions are? I did not find that in the spec.

It is used to specify the canonical name for an email (see second paragraph [here](https://git-scm.com/docs/git-check-mailmap#_mapping_authors)). So, actually it's enough to add `Geordie McBain <gdmcbain@protonmail.com>`.

**Comment by renefritze** [comment]
Ooops, typod the username in the commit, sorry.

**Pull request merged**
