### PR TITLE
Make eigs a bit more robust w.r.t. breakdowns in arnoldi iteration

### LINKED ISSUE #2280: eigs fails for operators on small dimensional spaces
```python
import numpy as np
from pymor.basic import NumpyMatrixOperator
from pymor.algorithms.eigs import eigs
eigs(NumpyMatrixOperator(np.eye(2)), k=1)
```

fails at `assert l > k`.

```python
import numpy as np
from pymor.basic import NumpyMatrixOperator
from pymor.algorithms.eigs import eigs
eigs(NumpyMatrixOperator(np.eye(3)), k=1)
```

fails in `_arnoldi` at `return V[:l], H, v * R[l, l]` with an `IndexError`.

### PR DESCRIPTION
**Pull request by sdrave**
Fixes #2280.

### CODE REVIEW

**Comment by pmli** [comment]
The example `eigs(NumpyMatrixOperator(np.eye(2)), k=1)` still fails, but `eigs(NumpyMatrixOperator(np.eye(2)), k=1, l=2)` works. Maybe it's ok to change how `l` is computed in `eigs`.

**Comment by sdrave** [comment]
> The example `eigs(NumpyMatrixOperator(np.eye(2)), k=1)` still fails, but `eigs(NumpyMatrixOperator(np.eye(2)), k=1, l=2)` works. Maybe it's ok to change how `l` is computed in `eigs`.

Hmm, for `eigs(NumpyMatrixOperator(np.eye(1)), k=1)` everything fails since one requires `l > k`. Maybe it is viable fix to call `to_matrix` for very small problems, say `n < 10` or so?

**Comment by pmli** [comment]
> > The example `eigs(NumpyMatrixOperator(np.eye(2)), k=1)` still fails, but `eigs(NumpyMatrixOperator(np.eye(2)), k=1, l=2)` works. Maybe it's ok to change how `l` is computed in `eigs`.
> 
> Hmm, for `eigs(NumpyMatrixOperator(np.eye(1)), k=1)` everything fails since one requires `l > k`. Maybe it is viable fix to call `to_matrix` for very small problems, say `n < 10` or so?

Sure, I guess.

**Comment by sdrave** [comment]
`eigs` now falls back to `scipy.linalg.eigs` in case `n - 1 < l_min`. Any further comments, @pmli, @drittelhacker? Otherwise, I will merge this soon as #2177 kind of depends on it.

**Review by pmli — APPROVED** [review]

**Pull request merged**
