### PR TITLE
resolve all remaining flake8 issues (fixes #1551)

### LINKED ISSUE #1551: unresolved Flake8 issues
To summarize #1547 (please correct me if I missed anything @artpelling):

There's a bunch (around 32) of docstrings violating D205 that should be dealt with. Options:
1. ignore D205 globally
1. mark only offending to be ignored
1. reword offending docstrings

I don't like option 1. I like the third the best, but that could be hard in places. I'm fine with option 2. as a compromise. Once we agree on the resolution this becomes a 'good first issue'.

There's a single digit amount each of D202, D402, D403, W505 too, but those should be straightforward to fix with no additional discussion necessary IMO.

If we include `docs` in the `flake8` run (ie with `pre-commit run -a`), there's a few F821 to fix too.

### PR DESCRIPTION
**Pull request by artpelling**
I have resolved all basic flake8 issues here that were not related to the docstrings. As mentioned in #1551, there are 34 issues left to solve, 32 of which are `D205 1 blank line required between summary line and description`.

Going by what @sdrave preached today, I looked at the history to find out who is to blame.

The award for most issues in one file goes to @pmli and `./src/pymor/discretizers/builtin/grids/interfaces` with a whopping 19 of 20 total D205 in that file 🏆 

The remaining 14 issues are listed below:

@sdrave:
- [x] `./src/pymordemos/burgers_ei.py:57:1: D205 1 blank line required between summary line and description`
- [x] `./src/pymor/core/logger.py:66:1: D205 1 blank line required between summary line and description`
- [x] `./src/pymor/discretizers/builtin/cg.py:1217:1: D205 1 blank line required between summary line and description`
- [x] `./src/pymor/parameters/base.py:92:1: D202 No blank lines allowed after function docstring`
- [x] `./src/pymor/parameters/base.py:92:1: D205 1 blank line required between summary line and description`
- [x] `./src/pymor/analyticalproblems/domaindescriptions.py:254:1: D205 1 blank line required between summary line and description`

@pmli:
- [x] `./src/pymordemos/analyze_pickle.py:244:1: D205 1 blank line required between summary line and description`
- [x] `./src/pymordemos/analyze_pickle.py:244:1: D403 First word of the first line should be properly capitalized`
- [x] `./src/pymor/discretizers/builtin/gui/jupyter/threejs.py:287:1: D205 1 blank line required between summary line and description`

@renefritze:
- [x] `./src/pymor/core/base.py:320:1: D205 1 blank line required between summary line and description`
- [x] `./src/pymor/discretizers/builtin/cg.py:114:1: D205 1 blank line required between summary line and description`
- [x] `./src/pymor/parameters/functionals.py:429:1: D205 1 blank line required between summary line and description`
- [x] `./src/pymor/parameters/functionals.py:491:1: D205 1 blank line required between summary line and description`
- [x] `./src/pymor/parameters/base.py:349:1: D205 1 blank line required between summary line and description`

Fixes #1551

### CODE REVIEW

**Comment by renefritze** [comment]
Thanks a lot for the work and putting us to shame :wink:

**Comment by artpelling** [comment]
> Thanks a lot for the work and putting us to shame 😉

Jokes aside, this is probably the easiest way as I don't understand half the methods and sometimes quite some rewording is required.

**Comment by renefritze** [comment]
Yeah, I completely agree :+1:

**Comment by sdrave** [comment]
@renefritze, I removed the `|lFEfunc|` substition again, as I found it distracting when reading the source code. Feel free to revert my last commit in case you disagree with the change.

**Comment by artpelling** [comment]
I double checked, no more errors now

**Pull request merged**
