### PR TITLE
[readme] feature the new logo

### PR DESCRIPTION
**Pull request by renefritze**
Follow up to #1076

### CODE REVIEW

**Comment by renefritze** [comment]
[For your viewing  pleasure](https://github.com/pymor/pymor/blob/readme_logo/README.md)

**Comment by sdrave** [comment]
Whoops ... #1080

**Comment by sdrave** [comment]
@renefritze, so you go ahead and merge one of the PRs. On my machines, I find my version a bit more visually pleasing (I think in your version the logo is a bit too large), but I really don't know how the browser chooses the size and how it looks on higher resolution displays ...

**Comment by renefritze** [comment]
Alright. Merging this one. Bigger is better :wink:

**Pull request merged**
