### PR TITLE
test against numpy master and check warnings

### PR DESCRIPTION
**Pull request by renemilk**
As a compromise between for a complete test suite on travis and addressing #358 I propose adding one single additional builder that installs numpy from git master, (re-)enables Warning capture and also turns of deprecation warning filtering. 

See also https://github.com/pytest-dev/pytest/issues/2586

### CODE REVIEW

**Comment by renemilk** [comment]
This can be merged, @sdrave.

**Comment by sdrave** [comment]
This seems like a useful addition to our test suite. However, what is happening with the appveyor tests?

**Comment by renemilk** [comment]
I haven't the foggiest. My plan was to ignore the weird BS failures it gives until I get to using Docker there too.

**Comment by renemilk** [comment]
The allow fail stuff worked on appveyor, @sdrave. I'll merge later today

**Comment by sdrave** [comment]
@renemilk, are you sure? Github still says "Some checks were not successful" and there is still a red "x" for this PR in the list of PRs.

**Comment by renemilk** [comment]
Yes, I am sure. That's cause appveyor cannot build the PR due to the merge conflict. The branch build is green despite the individual builds all failing.

**Comment by sdrave** [comment]
Ah, ok.

**Comment by renemilk** [comment]
Merged

**Pull request closed without merging**
