### PR TITLE
add ns_liddrivencavity_fenics.py

### PR DESCRIPTION
**Pull request by mdessole**
I added the instationary lid driven cavity benchmark.

### CODE REVIEW

**Comment by HenKlei** [comment]
Thank you very much @mdessole for the contribution. I will take a closer look at the code in the next days.

**Comment by HenKlei** [comment]
@mdessole could you take a look at [this branch on my fork](https://github.com/HenKlei/pymor/tree/feature/navier-stokes) please?

I simply copied your main branch and made a couple of changes to your code, but the general structure stayed the same. What is still missing is the empirical interpolation to obtain real speedups. If I remember correctly, there was a problem with the boundary condition treatment in the empirical interpolation for the velocity. I will take a look at that next.

**Comment by sdrave** [comment]
> The problem is reproduced [here](https://github.com/HenKlei/pymor/tree/bug/fenics-bindings). Maybe @sdrave immediately sees what I'm doing wrong?

I think I have fixed the Issue in @HenKlei's branch. More testing is needed, however.

**Comment by renefritze** [comment]
Continued in #1673

**Pull request closed without merging**
