### PR TITLE
Improve data visualization in notebooks

### PR DESCRIPTION
**Pull request by renefritze**
This PR adds a mini library that translates between our VTK output to disk and [K3D](https://github.com/K3D-tools/K3D-jupyter). There's a new `notebooks/elliptic.ipynb` that demos the visualization with a slider (currently mis-labeled as timesteps). Click below.

[Binder](https://mybinder.org/v2/gh/pymor/pymor/notebook_vis?filepath=elliptic.ipynb)

### CODE REVIEW

**Comment by renefritze** [comment]
referencing #647, the implementation in this PR does:

Minimal:
 - [x] 2D only view of 2D (point+cell, scalar) data (rotate/zoom controls not locked yet though)
 - [x] time series support
 - [ ] notebook embeddable (visualization is usable w/o executing the cell after opening the notebook)
 - [x] colorbar 
 - [ ] "good" default color map
 - [ ] "play" controls for time series/multi param arrays

Nice to have: 
 - [x] 3D data with cut plane/thresholding support (no thresholding, but cut planes can be added)
 - [ ] vector valued functions
 - [ ] static representation (nbviewer)
 - [ ] warp-by-scalar elevation plot like visualization 
 - [ ] live appending of data
 - [x] selectable color maps
 - [ ] multiple parallel data views

**Comment by renefritze** [comment]
The k3d based visualization now ticks all but one of the "minimal" boxes. Check it out, @pymor/pymor-devs (and please don't mind the controls box or the still-displaying grid):
[Binder](https://mybinder.org/v2/gh/pymor/pymor/notebook_vis?filepath=elliptic.ipynb)

**Comment by renefritze** [comment]
@sdrave https://github.com/pymor/pymor/pull/629/commits/7b3dc127164330752324ce0209b92fb5385998a0

**Comment by renefritze** [comment]
Also https://github.com/pymor/pymor/pull/629/commits/1fe9088f959e5d7a23f3bd08b40eb9ffc227dd65

**Comment by renefritze** [comment]
https://github.com/pymor/pymor/pull/629/commits/b23eb2c6b969130dfc87db6ca13df389f98070c3 should give you what you wanted wrt per-cell logging redirect, @sdrave 

I'm also half-way there concerning the last 'must-have' on the checklist. See https://pymor.org/stuff/jupyter/embbeded_plot_example.html for an example of what one now gets if you do: trust notebook -> rerun -> menu: (widgets -> save notebook widget state) -> save as html
There's no connection between controls and plot any longer ofc. For this I need to clear https://github.com/K3D-tools/K3D-jupyter/issues/138 before I try to add JS play controls. 
There's also a reset of/not loading of the camera setup, which needs fixing.

**Comment by sdrave** [comment]
@renefritze, regarding the progress bar, you might also want to check out tqdm. I quite like to use it on the console and it also has jupyter integration:
https://github.com/tqdm/tqdm#ipythonjupyter-integration

**Comment by renefritze** [comment]
A tiny update brings us built-in color legend and unmoveable camera.

**Comment by renefritze** [comment]
Some more questions to check:

 - more than one vectorarray display
 - local kernel display responsiveness
 - other features of the Qt based visualization missing?
 - per plot colorbar or not
 - auto (re-) scaling of timeseries data
 - plot titles

**Comment by renefritze** [comment]
I've prototyped a vispy-based visualizer, which seems much more promising performance wise. I'll prepare a new PR without the k3d stuff shortly

**Pull request closed without merging**
