### PR TITLE
[WIP] generic Dirichlet shift

### PR DESCRIPTION
**Pull request by ftalbrecht**
I would like to use this pr to discuss possible algorithmic requirements to automatically handle the Dirichlet shift that is required for MOR of problems with non-homogeneous Dirichlet data (see below for a MWE). Questions to consider (among others) are:

* do we want to support some generic processing at all?
* if yes, should this happen in the discretizer already or is this a postprocessing of the fom (I currently favor the former)
* if yes, do we provide a shifted visualize?

### CODE REVIEW

**Comment by ftalbrecht** [comment]
My currently used workflow is something like the following `.md` file which you can turn into a script or notebook which is supposed to be used with this branch.

```python
%autosave 0
%matplotlib notebook

import numpy as np
from pymor.basic import *
```

```python
from pymor.analyticalproblems.thermalblock import thermal_block_problem
problem = thermal_block_problem(num_blocks=(1, 1))
problem = problem.with_(dirichlet_data=ExpressionFunction('x[..., 0] < 1e-7', dim_domain=2))
problem = problem.with_(outputs=(('l2', ConstantFunction(1., dim_domain=2)),))
```

```python
fom, fom_data = discretize_stationary_cg(problem)
```

# Dirichlet correction

Consider the problem of finding $u \in H^1(\Omega)$, such that

$$\begin{align}
a(u, v) &= l(v) &&\text{for all }v \in H^1_0(\Omega),\\
u &= g_D &&\text{on }\partial\Omega,
\end{align}$$

Then $u_0 := u - g_G \in H^1_0(\Omega)$, and we equivalently look for $u = u_0 + g_D \in H^1(\Omega)$, such that

$$\begin{align}
a(u_0 + g_G, v) &= l(v) &&\text{for all }v \in H^1_0(\Omega),\\
\end{align}$$

that is: we look for $u_0 \in H^1_0(\Omega)$, such that

$$\begin{align}
a(u_0, v) &= l(v) - a(g_G, v) &&\text{for all }v \in H^1_0(\Omega).\\
\end{align}$$

```python
from pymor.operators.cg import BoundaryInterpolationOperator
g_D_op = BoundaryInterpolationOperator(fom_data['grid'], problem.dirichlet_data, fom_data['boundary_info'], 'dirichlet')
g_D = g_D_op.assemble().as_range_array()
```

```python
from pymor.operators.constructions import Concatenation, ConstantOperator, IdentityOperator

dirichlet_shift = IdentityOperator(fom.solution_space) + ConstantOperator(g_D, fom.solution_space)
dirichlet_rhs_correction = Concatenation((fom.operator, g_D_op))

dc_fom = fom.with_(
    rhs=(fom.rhs - dirichlet_rhs_correction),
    output_functional=Concatenation((fom.output_functional, dirichlet_shift))
)
```

```python
for mu in fom.parameter_space.sample_randomly(3):
    u = fom.solve(mu=mu)
    u_0 = dc_fom.solve(mu=mu)
    print('state dirichlet correction error (mu={}) = {}'.format(mu, (u - dirichlet_shift.apply(u_0)).sup_norm()[0]))
    s = fom.output_functional.apply(u)
    dc_s = dc_fom.output_functional.apply(u_0)
    print('output dirichlet correction error (mu={}) = {}'.format(mu, (s - dc_s).sup_norm()[0]))
```

# Standard RB greedy, $H^1_0$-norm


```python
reductor = CoerciveRBReductor(dc_fom, product=dc_fom.h1_0_semi_product)
training_set = dc_fom.parameter_space.sample_uniformly(3)
greedy_data = rb_greedy(dc_fom, reductor, training_set)
```

**Comment by ftalbrecht** [comment]
Currently, this gives the following error:

```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-7-a93749b8194c> in <module>
      1 reductor = CoerciveRBReductor(dc_fom, product=dc_fom.h1_0_semi_product)
      2 training_set = dc_fom.parameter_space.sample_uniformly(3)
----> 3 greedy_data = rb_greedy(dc_fom, reductor, training_set)

~/residual-lrb-arbilomod/pymor/src/pymor/algorithms/greedy.py in rb_greedy(fom, reductor, training_set, use_estimator, error_norm, atol, rtol, max_extensions, extension_params, pool)
    201     surrogate = RBSurrogate(fom, reductor, use_estimator, error_norm, extension_params, pool or dummy_pool)
    202 
--> 203     result = weak_greedy(surrogate, training_set, atol=atol, rtol=rtol, max_extensions=max_extensions, pool=pool)
    204     result['rom'] = surrogate.rom
    205 

~/residual-lrb-arbilomod/pymor/src/pymor/algorithms/greedy.py in weak_greedy(surrogate, training_set, atol, rtol, max_extensions, pool)
     81     while True:
     82         with logger.block('Estimating errors ...'):
---> 83             max_err, max_err_mu = surrogate.evaluate(training_set)
     84             max_errs.append(max_err)
     85             max_err_mus.append(max_err_mu)

~/residual-lrb-arbilomod/pymor/src/pymor/algorithms/greedy.py in evaluate(self, mus, return_all_values)
    225         if self.rom is None:
    226             with self.logger.block('Reducing ...'):
--> 227                 self.rom = self.reductor.reduce()
    228 
    229         if not isinstance(mus, RemoteObjectInterface):

~/residual-lrb-arbilomod/pymor/src/pymor/reductors/basic.py in reduce(self, dims)
     68 
     69         if self._last_rom is None or any(dims[b] > self._last_rom_dims[b] for b in dims):
---> 70             self._last_rom = self._reduce()
     71             self._last_rom_dims = {k: len(v) for k, v in self.bases.items()}
     72 

~/residual-lrb-arbilomod/pymor/src/pymor/reductors/basic.py in _reduce(self)
     84         if self.assemble_estimator.__func__ is not ProjectionBasedReductor.assemble_estimator:
     85             with self.logger.block('Assembling error estimator ...'):
---> 86                 estimator = self.assemble_estimator()
     87         else:
     88             estimator = None

~/residual-lrb-arbilomod/pymor/src/pymor/reductors/coercive.py in assemble_estimator(self)
     48 
     49     def assemble_estimator(self):
---> 50         residual = self.residual_reductor.reduce()
     51         estimator = CoerciveRBEstimator(residual, tuple(self.residual_reductor.residual_range_dims),
     52                                         self.coercivity_estimator)

~/residual-lrb-arbilomod/pymor/src/pymor/reductors/residual.py in reduce(self)
     79                                                     (self.residual_range, self.residual_range_dims),
     80                                                     orthonormalize=True, product=self.product,
---> 81                                                     riesz_representatives=self.riesz_representatives)
     82                 except ImageCollectionError as e:
     83                     self.logger.warning(f'Cannot compute range of {e.op}. Evaluation will be slow.')

~/residual-lrb-arbilomod/pymor/src/pymor/algorithms/image.py in estimate_image_hierarchical(operators, vectors, domain, extends, orthonormalize, product, riesz_representatives)
    203             new_image = estimate_image(operators, vectors, None, extends=False,
    204                                        orthonormalize=False, product=product,
--> 205                                        riesz_representatives=riesz_representatives)
    206         else:
    207             new_image = estimate_image(operators, [], domain[i], extends=True,

~/residual-lrb-arbilomod/pymor/src/pymor/algorithms/image.py in estimate_image(operators, vectors, domain, extends, orthonormalize, product, riesz_representatives)
     90         for v in vectors:
     91             try:
---> 92                 rules.apply(v)
     93             except NoMatchingRuleError as e:
     94                 raise ImageCollectionError(e.obj)

~/residual-lrb-arbilomod/pymor/src/pymor/algorithms/rules.py in apply(self, obj)
    267             if r.matches(obj):
    268                 try:
--> 269                     result = r.action(self, obj)
    270                     self._cache[obj] = result
    271                     return result

~/residual-lrb-arbilomod/pymor/src/pymor/algorithms/image.py in action_recurse(self, op)
    266     @match_class(LincombOperator, SelectionOperator)
    267     def action_recurse(self, op):
--> 268         self.apply_children(op)
    269 
    270     @match_class(Concatenation)

~/residual-lrb-arbilomod/pymor/src/pymor/algorithms/rules.py in apply_children(self, obj, children)
    302                 result[child] = {k: self.apply(v) if v is not None else v for k, v in c.items()}
    303             elif isinstance(c, Iterable):
--> 304                 result[child] = tuple(self.apply(v) if v is not None else v for v in c)
    305             else:
    306                 result[child] = self.apply(c) if c is not None else c

~/residual-lrb-arbilomod/pymor/src/pymor/algorithms/rules.py in <genexpr>(.0)
    302                 result[child] = {k: self.apply(v) if v is not None else v for k, v in c.items()}
    303             elif isinstance(c, Iterable):
--> 304                 result[child] = tuple(self.apply(v) if v is not None else v for v in c)
    305             else:
    306                 result[child] = self.apply(c) if c is not None else c

~/residual-lrb-arbilomod/pymor/src/pymor/algorithms/rules.py in apply(self, obj)
    267             if r.matches(obj):
    268                 try:
--> 269                     result = r.action(self, obj)
    270                     self._cache[obj] = result
    271                     return result

~/residual-lrb-arbilomod/pymor/src/pymor/algorithms/image.py in action_Concatenation(self, op)
    274         else:
    275             firstrange = op.operators[-1].range.empty()
--> 276             self.apply(op.first, firstrange)
    277             CollectOperatorRangeRules(firstrange, image, False).apply(op.with_(operators=op.operators[:-1]))

AttributeError: 'Concatenation' object has no attribute 'first'
```

**Comment by ftalbrecht** [comment]
Fixed by #814

**Comment by renefritze** [comment]
Just FYI, @ftalbrecht you create new PRs in "draft" mode. Since that's visually represented by GitHub and the merge button is blocked I find that better than the '[WIP]' topic marker.

**Comment by ftalbrecht** [comment]
> Just FYI, @ftalbrecht you create new PRs in "draft" mode. Since that's visually represented by GitHub and the merge button is blocked I find that better than the '[WIP]' topic marker.

Did not know that, sounds good. Any idea how to apply this a posteriori?

**Comment by renefritze** [comment]
Doesn't look like there is a way to go from non-draft back to draft :disappointed: 
And ofc I promptly forgot to use draft in #829 myself :roll_eyes:

**Comment by renefritze** [comment]
There's now a link action to convert to draft, right below "Reviewers" in the right bar, @ftalbrecht

**Comment by sdrave** [comment]
@ftalbrecht, is it ok to close this PR? There seems to be other stuff included not related to dirichlet boundaries, which should probably go into a separate PR. Regarding handling of Dirichlet boundaries, there's know #1410, which will be followed by related PRs.

**Comment by ftalbrecht** [comment]
> @ftalbrecht, is it ok to close this PR? There seems to be other stuff included not related to dirichlet boundaries, which should probably go into a separate PR. Regarding handling of Dirichlet boundaries, there's know #1410, which will be followed by related PRs.

There is still the `simplify` in here, but once we need something alike you will easily come up with something better. So, no objections!

**Pull request closed without merging**
