### PR TITLE
Fix 643 in 0.5.x branch

### PR DESCRIPTION
**Pull request by sdrave**
Backport of #716.

### CODE REVIEW

**Comment by renefritze** [comment]
Tests have passed locally @sdrave, travis should follow in the next couple of hours :roll_eyes:

**Comment by renefritze** [comment]
ALso cherry-picked slycot pinning from master, that should get rid of the current deploy check failure

**Comment by sdrave** [comment]
Hmm still failing, but only in install_check. Can we safely merge this?

**Comment by renefritze** [comment]
The failure on looks somewhat bad. I'd like to take a look at that before merge.

**Comment by renefritze** [comment]
I'll re-run those checks with after I've updated to docker base images

**Comment by renefritze** [comment]
Debian is OK now. Centos wants to build an unreleased numpy for some reason, but I vote for ignoring that for now, @sdrave

**Pull request merged**
