### PR TITLE
Python 3 port

### PR DESCRIPTION
**Pull request by renemilk**
Opening this to get Travis going with python 3, refs #128.

### CODE REVIEW

**Comment by renemilk** [comment]
FYI the 2% health decrease is mostly due to running an additional tool.

**Comment by renemilk** [comment]
After the last push only 247 of 1598 tests still fail.

**Comment by renemilk** [comment]
There's actually a subset of tests that now work: https://travis-ci.org/pymor/pymor/jobs/84875073

**Comment by renemilk** [comment]
FYI: cleaned up the old landscape bot comments

**Comment by renemilk** [comment]
The real report is at https://landscape.io/github/pymor/pymor/417 btw and it's looking pretty good.

**Comment by sdrave** [comment]
Any idea why the python 3 branch is doing so good on landscape?

**Comment by renemilk** [comment]
Not really, no.

**Comment by renemilk** [comment]
@sdrave  could you please check out the remaining test failures in operators? I've got no clue.
Otherwise, at least on my box, only fenics tests remain failing.

**Comment by renemilk** [comment]
It is now possible to have the python3_move branch cheched out and run ```python2 setup.py test``` without error. Py3 tests currently still fail due to missing dolfin.

**Comment by ftalbrecht** [comment]
After manually installing `3to2` I can execute `python2 setup.py test` on my machine. I get a bunch of errors which are probably related to missing dependencies in my virtualenv. I could investigate further if desired. Apart from that it seems to work fine...

**Comment by renemilk** [comment]
Yes, please. Aside from fenics, which is a hard dependency for some tests, but not a requirement, you should not get any errors as everything should be downloaded by setup.py.

**Comment by ftalbrecht** [comment]
So, in a clean virtualenv, generated by
```bash
virtualenv2 --python=python2.7 --no-site-packages
```
running `python setup.py test` with `python --version: Python 2.7.11` yields the following output:
```python
{'build_py': <class __main__.build_py27 at 0x7fd466c377a0>}
Traceback (most recent call last):
  File "setup.py", line 245, in <module>
    setup_package()
  File "setup.py", line 225, in setup_package
    cmdclass=cmdclass,
  File "setup.py", line 154, in _setup
    _numpy_monkey()
  File "setup.py", line 40, in _numpy_monkey
    from numpy.distutils.misc_util import appendpath
ImportError: No module named numpy.distutils.misc_util
```
So in my case, numpy at least was not installed...

**Pull request closed without merging**
