### PR TITLE
make RTD use python 3.6

### PR DESCRIPTION
**Pull request by renefritze**

### CODE REVIEW

**Comment by renefritze** [comment]
Just fyi, @pymor/pymor-devs, labels also work nicely with the hub client:

`hub pull-request -l "type: fix" -l "buildsystem" -m "make RTD use python 3.6"
`

**Comment by sdrave** [comment]
I guess before polluting master with ten PRs of this type, we should enable this branch on RTD and test it first?

**Comment by renefritze** [comment]
Already done: https://readthedocs.org/projects/pymor/builds/8466176/

**Comment by renefritze** [comment]
Note to self: when CI is done, disable and wipe version in RTD

**Pull request merged**
