### PR TITLE
Set gram_schmidt tolerances in POD to 0 to never truncate pod modes

### LINKED ISSUE #961: POD singular values not truncated when gram_schmidt removes vectors
Referencing https://github.com/pymor/pymor/pull/910#discussion_r442739587 @sdrave thinks 8d0dfb8ebe7759d914205daec46de62f67587468 and 0b1e1708ccccfc67081eacbb4c10e75f989bdefa might mask an actual bug and not just a change in input data due to hypothesis.

### PR DESCRIPTION
**Pull request by sdrave**
Fixes #961.

### CODE REVIEW

**Comment by sdrave** [comment]
@renefritze, here we have another failed build that has no hash for reproducing and very long error message.

**Comment by renefritze** [comment]
That actually looks like the log was cut. I'm making the hypothesis dir downloadable to better debug cases like this. The new push might just clear the error too though.

**Comment by renefritze** [comment]
@sdrave https://zivgitlab.uni-muenster.de/pymor/pymor/-/jobs/357536#L13514

**Comment by sdrave** [comment]
@renefritze, I can't reproduce the failures locally. Can you?

Also, why are there so many 'Trying example:' blocks? I still don't really understand the output. There are also two different 'reproduce_failure' decorators mentioned. Why?

**Comment by renefritze** [comment]
> I can't reproduce the failures locally. 

Even using the right docker image?

> Also, why are there so many 'Trying example:' blocks?

An "example" is one input state for the test function. `max_examples` is `100` for pull requests.

> There are also two different 'reproduce_failure' decorators mentioned. Why?

Cause it found multiple failures.

**Comment by sdrave** [comment]
> >  I can't reproduce the failures locally.

> Even using the right docker image?

Yes.

> >   Also, why are there so many 'Trying example:' blocks?

> An "example" is one input state for the test function. max_examples is 100 for pull requests.

But why do I see the output for all these examples? Can this be turned of?

> >    There are also two different 'reproduce_failure' decorators mentioned. Why?

> Cause it found multiple failures.

I would have assumed that it stops when it finds a failing example. Is the second one the 'reduced' version?

**Comment by renefritze** [comment]
> But why do I see the output for all these examples? 

I think you'll have to ask the library authors for this.

> Can this be turned of?

Haven't seen a setting that controls output, but I haven't looked for one.

> I would have assumed that it stops when it finds a failing example. Is the second one the 'reduced' version?

> E   hypothesis.errors.MultipleFailures: Hypothesis found 2 distinct failures.

You can make hypothesis stop after it found one though, but I don't think that's a good choice for CI.

**Comment by sdrave** [comment]
> > Can this be turned of?

> Haven't seen a setting that controls output, but I haven't looked for one.

In `conftext.py` you have set the verbosity of hyporthesis to `verbose`. If I understand the code correctly, setting it to normal should print only failing examples.

**Comment by sdrave** [comment]
So after rebasing on master, the hypothesis failure is gone, but I suspect we will see it again at some point .. - @renefritze should this be merged with 7e869c3 still in it?

**Comment by renefritze** [comment]
> So after rebasing on master, the hypothesis failure is gone, but I suspect we will see it again at some point .. - @renefritze should this be merged with [7e869c3](https://github.com/pymor/pymor/commit/7e869c3c8c6b55172e62be895991924569621316) still in it?

Yes. That doesn't hurt and can be useful in a future occurrence.

**Pull request merged**
