### PR TITLE
fix typos

### PR DESCRIPTION
**Pull request by ftalbrecht**
merge when ready

### CODE REVIEW

**Comment by renefritze** [comment]
> merge when ready

That has been replaced: https://github.com/pymor/pymor/pull/907

**Comment by ftalbrecht** [comment]
Thx for the info, applied the label. However, there seems to be other trouble...

**Comment by renefritze** [comment]
Errors be gone :mage_man:

**Comment by ftalbrecht** [comment]
I need that magic wand! :) Thx

**Pull request merged**
