### PR TITLE
Remove as_source/range_array in solve_sylv_schur

### PR DESCRIPTION
**Pull request by pmli**
This avoids the bug in #624 and somewhat simplifies the implementation.

### CODE REVIEW

**Comment by pmli** [comment]
Good point, I've added a few sentences.

**Comment by renefritze** [comment]
Did you assign me by accident, @pmli?

**Comment by pmli** [comment]
@renefritze There was an issue with a GitLab test, which it seems you fixed already. 👍

**Comment by renefritze** [comment]
Ah, I see. #630 should help mitigate those instability issues too.

**Pull request merged**
