### PR TITLE
remove notebooks dir

### PR DESCRIPTION
**Pull request by renefritze**
This removes testing infrastructure for the notebooks  subdirectory
and nbconverts all notebooks to demos that did not already have a matching demo.

### CODE REVIEW

**Comment by renefritze** [comment]
I've based this in the typer branch, so this should only be merged after #1118

**Comment by renefritze** [comment]
My plan is to merge this ASAP and let @pmli take over making the "new" demos into something actually useful/useable. 

Sound good?

**Review by pmli — APPROVED** [review]

**Comment by sdrave** [comment]
I think before merging this, we should hook up the new demos into our testing infrastructure. For that one only would have to make each new demo a (trivial) typer app and add corresponding lines to `SYS_MOR_ARGS` in `pymortests.demos`.

**Comment by renefritze** [comment]
> I think before merging this, we should hook up the new demos into our testing infrastructure. For that one only would have to make each new demo a (trivial) typer app and add corresponding lines to `SYS_MOR_ARGS` in `pymortests.demos`.

That's easier todo when one actually makes the demos work anyhow. As is they might block execution due to non-NB visualization.

**Comment by sdrave** [comment]
So why do yo want to merge before the demos actually work? Do you have any reason to believe that the matplotlib hack in `_test_demo` won't work?

**Comment by renefritze** [comment]
As I explained in chat already, problems with the testing infra for notebooks currently interferes with the work I do on https://github.com/pymor/pymor/issues/876 and generally I did not want to solve problems with the demos now that might not even be there after @pmli changes them. Blocking show was just an example.

**Comment by sdrave** [comment]
Ok.

**Pull request merged**
