### PR TITLE
fix parse(mu) for a mu that is a Mu

### PR DESCRIPTION
**Pull request by ftalbrecht**
Otherwise `parameters.parse(mu)` fails, if `isinstance(mu, Mu)`. Was I really the first one to stumble upon this?

### CODE REVIEW

**Comment by renefritze** [comment]
I've switched auto-merge to "merge commit" since we decided to only use those for PRs.

**Comment by renefritze** [comment]
> Otherwise `parameters.parse(mu)` fails, if `isinstance(mu, Mu)`. Was I really the first one to stumble upon this?

Seems also to not be covered in the test suite then. Would be a good though.

**Comment by ftalbrecht** [comment]
> I've switched auto-merge to "merge commit" since we decided to only use those for PRs.

thx

**Comment by ftalbrecht** [comment]
> > Otherwise `parameters.parse(mu)` fails, if `isinstance(mu, Mu)`. Was I really the first one to stumble upon this?
> 
> Seems also to not be covered in the test suite then. Would be a good though.

Indeed. I've opened #1345, since I have less than no time atm.

**Comment by renefritze** [comment]
This is currently blocked by https://github.com/jupyterhub/repo2docker/issues/1063. Since that looks to be in the process of getting fixed, I'm not deploying a workaround.

**Comment by renefritze** [comment]
> This is currently blocked by [jupyterhub/repo2docker#1063](https://github.com/jupyterhub/repo2docker/issues/1063). Since that looks to be in the process of getting fixed, I'm not deploying a workaround.

Turns out the fix might not release as quickly as I hoped. Added 677d3bc894ef45baeac0f531556ef26d52258607 as a workaround

**Pull request merged**
