### PR TITLE
Output error bounds

### PR DESCRIPTION
**Pull request by TiKeil**
This PR adds output error bounds as discussed in #575 with the DWR approach.

### CODE REVIEW

**Comment by TiKeil** [comment]
> @TiKeil, only a gentle reminder to look into this PR. Please let me know when you want input from my side.

Thanks, I should have done this way earlier because I forgot all of it by now. I regathered this today and there is still some small work to do. So no comments needed from your side yet.

**Comment by TiKeil** [comment]
some comments:

- this code is only working for symmetric operators which means that I never use `operator.H` in the code. Using this gave some bugs in the `CoerciveRBReductor` and needs additional code in `SimpleCoerciveRBReductor`, so I would stay at the symmetric case for this PR and leave the unsymmetric case as a TODO leftover. The only problem is that we still do not have an assertion for this.
- I added a simple way of turning off the preassembling of estimators in general. For that I added a `assemble_error_estimate` and `assemble_output_error_estimate` argument for the `ProjectionBasedReductor`. As a generalization one could further think about the possiblity to choose a specific estimator which is to be assembled (if there are multiple ones available, as discussed in #1337). This can further be discussed after the release.
- So far I have only added a new `pymortest` without editing a demo or a tutorial. One could think about one of the other two options as well but for now, the `pymortest/outputs.py` already shows all features and tests this rigorously.
- I had to add an `apply_adjoint` method for the `ComponentProjectionOperator` which is rather unrelated but needed. I would say this can stay in this PR however.
- A bad thing about our currently implemented way of constructing an `output_functional` with multiple dimensions in our builtin discretizer is that we get a `BlockOperators` of `LincombOperators`. This of course is bad for the offline-online decomposition of the rhs of our dual problem. To circumvent this, one would need to treat vector valued outputs in a better way which however is not as trivial as I expected ( a `LincombOperator` of `BlockOperators` did not work out immediately). Anyway, the code still works for all cases (but is inefficient for the above discussed case).

Comments appreciated.

**Comment by renefritze** [comment]
You can rebase on main now instead of adding https://github.com/pymor/pymor/pull/1227/commits/a3ed8c6b2639572b3662cb48ffdd73e3e54c7e4c yourself. Thanks again for bringing that CI problem to my attention!

**Comment by renefritze** [comment]
Let's ping @sdrave again for the review.

**Comment by TiKeil** [comment]
This is not happening before the release. Moving to next release.

**Comment by TiKeil** [comment]
closing since #1418 works as a replacement. Code for `SimpleCoerciveReductor` might still be relevant.

**Pull request closed without merging**
