### PR TITLE
Some fixes for the tutorials

### PR DESCRIPTION
**Pull request by HenKlei**
This PR fixes issues with cells that should be hidden but are not and missing math highlighting. Further, the background of the figures in the tutorials is now transparent, which looks much nicer in my opinion.

### CODE REVIEW

**Comment by HenKlei** [comment]
The failing link checker made me aware of the fact that the paper linked in the tutorial is meanwhile published, right @TiKeil? I updated the link accordingly.

**Comment by HenKlei** [comment]
When building the docs locally using `make docs`, also the time series plots are created without the white "border". Building with `make docker_docs` results in the white "border"s again. I am not sure why this is the case actually.

**Comment by HenKlei** [comment]
The commits [bd651af](https://github.com/pymor/pymor/pull/1960/commits/bd651af973eb5aac0d45c75e9626877eb0281853) and [fc174f6](https://github.com/pymor/pymor/pull/1960/commits/fc174f6d5a36db3820f666b2ea02d0704566e222) fix bugs with the visualizers. The problem with the limits of the colorbar can be seen in the first figure in [the optimization tutorial](https://docs.pymor.org/main/tutorial_optimization.html).

**Review by sdrave — COMMENTED** [review]
Looks good. @HenKlei, could you open a separate pr for the colormap fix. Not really tutorial related ..

**Review by sdrave — APPROVED** [review]

**Comment by HenKlei** [comment]
Building the docs locally using `make docker_docs` results in nice transparent backgrounds after [3bbdd8e](https://github.com/pymor/pymor/pull/1960/commits/3bbdd8e510f9ad62bf83b9cb43d0cdbf1b9915c7) for all plots, in particular also for the animated ones. However, the docs built during the pipeline look different, see [here](https://docs.pymor.org/fixes-tutorials/tutorial_basis_generation.html). I am not sure why this is the case and probably have to try different settings to see if one of them works.

Further, unfortunately, `patch.alpha` is not a key for `rcParams`, so I had to adjust the transparency directly in the visualizer. This is not optimal, but I think it is okay for now. What do you think @sdrave?

**Comment by HenKlei** [comment]
Could you have a quick look @TiKeil if the paper linked to in your tutorial is the right one?

**Comment by TiKeil** [comment]
> Could you have a quick look @TiKeil if the paper linked to in your tutorial is the right one?

Yes is correct, sorry forgot to click on approval.

**Review by TiKeil — APPROVED** [review]

**Pull request merged**
