### PR TITLE
Remove some quirks for old numpy versions

### PR DESCRIPTION
**Pull request by sdrave**

### CODE REVIEW

**Comment by sdrave** [comment]
Regarding `INDEX_QUIRK` there was no documentation which minimal version is required. For `INDEX_TYPES` we need at least 1.9 (released in 2014). Thus, we should bump the minimal version.

**Comment by renefritze** [comment]
Without checking I'm pretty sure `INDEX_QUIRK` was for even older versions. Do you want to go to `1.12` which is the version currently in debian stable?

**Comment by sdrave** [comment]
If this is the oldest version we are currently running test for, then this might be a good choice.

**Comment by renefritze** [comment]
That is actually a pretty good I haven't considered before. We definitely _should_ test against the oldest "pinned" versions in our requirements explicitly. Maybe combined with the oldest supported python? 

Currently system packages are never considered in our CI runs, it's always with non-system python interpreter in debian-based images mixed with whatever restrictions requirement files impose.

**Comment by sdrave** [comment]
Ok, so with the PR we now require numpy>=1.12. - Maybe open an issue regarding testing of old versions?

**Comment by sdrave** [comment]
Yay, seems like Azure DevOps also has some issues sometimes. @renefritze, I don't have an account. Could you trigger the rebuild?

**Comment by renefritze** [comment]
Does the re-run link on the checks page not exist for you, @sdrave ? I always assumed that was available to everybody in the org. 
screenshot-github com-2019 03 15-17-25-19

**Comment by sdrave** [comment]
Ah sorry, didn't see that ...

**Pull request merged**
