### PR TITLE
report upload fix

### PR DESCRIPTION
**Pull request by renefritze**

### CODE REVIEW

**Comment by renefritze** [comment]
I would also suggest to reduce pytest's stdout verbosity and instead add an additional logfile with max verbosity @pymor/pymor-devs

**Comment by renefritze** [comment]
So I don't think that split is terribly useful. Have a look at a pipeline log from that: https://zivgitlab.uni-muenster.de/pymor/pymor/-/jobs/357932
And the separate Logfile: https://pymor.zivgitlabpages.uni-muenster.de/-/pymor/-/jobs/357932/artifacts/pytest.log

**Comment by sdrave** [comment]
> So I don't think that split is terribly useful.

I agree. I think, when hypthesis verbosity is reduced (see #980), the output is fine?

**Comment by sdrave** [comment]
@renefritze, what is the bot doing in this PR? Is this the automerge but automatically rebasing on master? I was not aware of this feature. Do we want that?

**Comment by renefritze** [comment]
Yeah, I just noticed. It's supposed to only do that if no FF merge is possible though.

**Comment by sdrave** [comment]
> Yeah, I just noticed. It's supposed to only do that if no FF merge is possible though.

Is this desirable? It will also trigger CI again. In combination with hypothesis it can make real errors just 'go away'.

**Comment by renefritze** [comment]
It would be, yes. But since it's working properly, no, it is not.

**Comment by renefritze** [comment]
#1002

**Pull request merged**
