### PR TITLE
Github action for flake8 check

### PR DESCRIPTION
**Pull request by renefritze**

### CODE REVIEW

**Comment by renefritze** [comment]
Please @pymor/all have a look at this PR. I found a tool that creates PR reviews from flake8 output. If you click on details for this action you can view all of the problems flake8 found, but the tool will only add review comments for problems that were added in the PR diff. I think this is pretty much what we discussed yesterday.

**Comment by TiKeil** [comment]
I agree, this is exactly what we were looking for.
Looks awesome.

**Comment by pmli** [comment]
Looks quite nice.
So, if the commented flake8 issues are fixed, the PR flake8 check should pass? Or will it fail when there are also issues outside the diff?

**Comment by renefritze** [comment]
> Looks quite nice.
> So, if the commented flake8 issues are fixed, the PR flake8 check should pass? Or will it fail when there are also issues outside the diff?

It should, but doesn't. Looks like I'm running into https://github.com/grantmcconnaughey/Lintly/issues/41 here. Trying with a pinned version in #1232

**Comment by pmli** [comment]
Great, thanks @renefritze. It looks good to me.

**Pull request merged**
