### PR TITLE
ci pre commit

### PR DESCRIPTION
**Pull request by renefritze**
- [docs] add notes for the pre-commit service
- [readme] add pre-commit badge

### CODE REVIEW

**Comment by renefritze** [comment]
@artpelling if you have the time, could you investigate why pre-commit [produced changes ](https://github.com/pymor/pymor/pull/1930/commits/f3d8bbd008ef542d1436ea07d4d4ccf62060830d) when this branch is based off of main, which has your ruff PR merged?

**Comment by HenKlei** [comment]
> @artpelling if you have the time, could you investigate why pre-commit [produced changes ](https://github.com/pymor/pymor/pull/1930/commits/f3d8bbd008ef542d1436ea07d4d4ccf62060830d) when this branch is based off of main, which has your ruff PR merged?

I ran ruff today on all files of main just to see what happens and it produced the exact same changes. And showed additional violations in `versioneer.py` (that were somehow not fixed automatically).

**Comment by renefritze** [comment]
Hmm, that's weird though. Unless @artpelling  always ran ruff only in the `src/` subdir?

What's weirder is that the pre-commit check itself now is still red, even for the commit where it added the changes.

**Comment by renefritze** [comment]
Manually added some more fixes. Hopefully that's stable now

**Comment by artpelling** [comment]
> Hmm, that's weird though. Unless @artpelling always ran ruff only in the `src/` subdir?

Yes. Sorry, I only ran it on `src`.

**Comment by renefritze** [comment]
> > Hmm, that's weird though. Unless @artpelling always ran ruff only in the `src/` subdir?
> 
> Yes. Sorry, I only ran it on `src`.

No worries. 

Check looks good now.

**Review by HenKlei — APPROVED** [review]
Looks good to me!

**Comment by renefritze** [comment]
The pre-commit check is now a required branch protection for main

**Pull request merged**
