### PR TITLE
[logger] add log indentation support via logger.block context manager

### PR DESCRIPTION
**Pull request by sdrave**
@ftalbrecht, you may have a strong opinion on this ...

### CODE REVIEW

**Comment by sdrave** [comment]
@ftalbrecht, as discussed, I have moved the timestamps to the left. I have also resolved the 'change of timestamp width' issue.

I am wondering: shouldn't also the bold printing be disabled when colors are disabled?

**Comment by ftalbrecht** [comment]
Very nice! Yes, I would think so. The whole point of disabling "colors" is to disable printing of any control characters, which would otherwise turn up as undesired output in certain terminal emulators...

**Comment by sdrave** [comment]
Bold font is now also disabled. I also moved the pipe characters to the left which looks a bit cleaner to my eye. If no one objects, I will merge this.

**Comment by ftalbrecht** [comment]
Can't look at it right now, but I trust you did the right thing...

**Pull request merged**
