### PR TITLE
[WIP] Use our Drone.io setup for CI

### PR DESCRIPTION
**Pull request by renefritze**

### CODE REVIEW

**Comment by renemilk** [comment]
I apparently fubared a rebase somewhat, these are not all the commits to be merged. 

OTOH, a complete test suite now works on drone and a single builder is currently around 2x faster. Drones do not yet deploy/build wheels though.

**Comment by renemilk** [comment]
That's better.

**Comment by renemilk** [comment]
For the actual test execution the drone setup is now on-par with travis. What's missing is wheel deployment and testlog upload. I think we should merge this PR as is and at some point in the future I'll do another PR for the missing stuff.

**Comment by renefritze** [comment]
Rebased on master again

**Comment by renefritze** [comment]
I want to update my drone setup from 0.8 to 1.0 before we can merge this.

**Comment by renefritze** [comment]
I'm closing this PR since we've come to the conclusion that for us it will be simpler to use GitlabCI connected to this repo instead of maintaining our own drone.io setup. I'll keep the branch for reference for a while though.

**Pull request closed without merging**
