### PR TITLE
Fix some deprecation/future warnings

### PR DESCRIPTION
**Pull request by renefritze**

### CODE REVIEW

**Comment by pmli** [comment]
How about other `warn` calls?
```
$ grep -rn 'warn(' src/pymor | grep -v 'warnings\.warn'
src/pymor/discretizers/builtin/grids/gmsh.py:86:        logger.warn('Boundary data not found. Creating empty BoundaryInfo ...')
src/pymor/discretizers/builtin/gui/qt.py:289:                    l.warn('separate_colorbars=False not supported for matplotlib backend')
src/pymor/discretizers/builtin/gui/gl.py:99:                getLogger('pymor.discretizers.builtin.gui.gl.colormap_texture').warn(msg)
src/pymor/algorithms/ei.py:325:                logger.warn('DEIM algorithm not parallel. Collecting operator evaluations.')
```

**Comment by renefritze** [comment]
> How about other `warn` calls?

Will get those too, yes. Thanks!

Guess those are not covered with tests or I overlooked the warnings in the log.

**Comment by renefritze** [comment]
Did you guys get a new review request btw? I wasn't aware that github hasn automatism for that (force push?). I did not request a re-review myself...

**Comment by pmli** [comment]
> Did you guys get a new review request btw? I wasn't aware that github hasn automatism for that (force push?). I did not request a re-review myself...

No, I just wanted to give an "official" approval.

**Pull request merged**
