### PR TITLE
Docopt fix

### PR DESCRIPTION
**Pull request by renefritze**
As mentioned elsewhere 0.5.2 hard to install downstream due to docopt not installing in pep 518 mode, which newer pips now default to. However the compatible fork doctop-ng I've now switched to in master is not usable with python 3.5. Therefore I'm here pulling the old docopt vendor commits here to fix this and if there are no objections will prepare 0.5.3 once this PR is green(-ish?).

### CODE REVIEW

**Comment by renefritze** [comment]
Anybody got a clou how/why we have this broken gmsh test in the 0.5.x branch? 
https://travis-ci.org/pymor/pymor/jobs/591494292#L1271

**Comment by sdrave** [comment]
@renefritze seems like we can only pars gmsh files of version 2.2 and the gmsh in the container generates a newer file format? No idea why there are no issues with master. Regarding master, we should probable go ahead with #680.

**Comment by renefritze** [comment]
> @renefritze seems like we can only pars gmsh files of version 2.2 and the gmsh in the container generates a newer file format?

I mean, yes. My actual question ofc was why this is not broken everywhere. 

> Regarding master, we should probable go ahead with #680.

Indeed.

**Comment by sdrave** [comment]
4b84e02b

**Comment by renefritze** [comment]
Forgot we're still testing pre 3.6 here :roll_eyes:

**Pull request merged**
