### PR TITLE
bump minimal pip supported for installation

### PR DESCRIPTION
**Pull request by renefritze**

### CODE REVIEW

**Comment by renefritze** [comment]
@pymor/pymor-devs all open PRs will have to rebase on master/cherry pick the one commit after this is merged.

**Comment by renefritze** [comment]
Waiting for docker-images to update before CI can succeed.

**Comment by sdrave** [comment]
Seems like now slycot fails to install ..

**Comment by renefritze** [comment]
That one isn't actually slycot's problem though. That's me setting up ccache the wrong way.

**Pull request merged**
