### PR TITLE
Wheel building

### LINKED ISSUE #402: Unkown Version in RTD builds
The version number of the latest master build on RTD is shown as `v0.unkown`.

### PR DESCRIPTION
**Pull request by renemilk**
The idea to not install mpi4py with 'most' comes from its failure to install into a vanilla debian as a dependency of our wheel: https://github.com/pymor/pymor/commit/c7d2cd316b82d981012588dce3ea93b04fcf8f3a

https://github.com/pymor/pymor/commit/80acad0596ffa1868afeb2f8a114de6a71ad21bf could maybe also fix #402 

TODO: 
- integrate wheel building into travis setup
- there's a few test failures remaining when testing against an installed whl

### CODE REVIEW

**Comment by renemilk** [comment]
Did we decide when we want to build wheels? From what source? Upload where?
Building wheels for git tags and upload to pypi is a given. But what else? Have something that needs ``--pre``` to install on pypi which is constantly updated from master?

**Comment by renemilk** [comment]
There's also the question of what tests to run on the generated wheel before uploading. Neither of our travis builds needs less than half the max allowed time. So building the wheel and testing the full suite on it again in existing builders isn't feasible. 
Either way, IMO uploading should only happen if all builder (tests) have already succeeded, meaning we're going to need to use the new-ish build-stage feature.

**Comment by renemilk** [comment]
Any opinions @pymor/pymor-devs

**Comment by ftalbrecht** [comment]
> Either way, IMO uploading should only happen if all builder (tests) have already succeeded
> - @renemilk 

agreed

**Comment by renemilk** [comment]
Just FYI: The travis builders now carry "python 3.6" in the description line. That's not relevant to what's tested, and only indicative of which python gets installed in the travis executor.

**Comment by renemilk** [comment]
What kind of retention policy do we want for http://wheels.pymor.org/index.html ? Keep the last N wheels per branch and python? N = 2 maybe?

**Comment by renemilk** [comment]
As discussed offline I'm now keeping the last 10 wheels online on the http://wheels.pymor.org/index.html 
There's links to latest for each branch and python version there too, which get updated automatically. For me this is now ready to merge.

**Comment by sdrave** [comment]
Awesome! But how do I install those wheels? Trying

    pip install http://wheels.pymor.org/pymor-master-latest-cp35-cp35m-manylinux1_x86_64.whl

yields

    pymor-master-latest-cp35-cp35m-manylinux1_x86_64.whl is not a valid wheel filename.

**Comment by renemilk** [comment]
I'm rolling my very hard at pip right now. I guess I'll have to add a bogus version string into the files.

**Comment by renemilk** [comment]
Yeah, so apparently you cannot simply rename the file and be done with it:
```
pip install http://wheels.pymor.org/pymor-master-latest-9999.9.rc0-cp35-cp35m-manylinux1_x86_64.whl
Collecting pymor-master-latest==9999.9.rc0 from http://wheels.pymor.org/pymor-master-latest-9999.9.rc0-cp35-cp35m-manylinux1_x86_64.whl
  Downloading http://wheels.pymor.org/pymor-master-latest-9999.9.rc0-cp35-cp35m-manylinux1_x86_64.whl (644kB)
    100% |████████████████████████████████| 645kB 4.3MB/s 
<SNIP>
Installing collected packages: pymor-master-latest
Exception:
Traceback (most recent call last):
  File "/tmp/fefe/lib/python3.5/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/tmp/fefe/lib/python3.5/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/tmp/fefe/lib/python3.5/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/tmp/fefe/lib/python3.5/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/tmp/fefe/lib/python3.5/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/tmp/fefe/lib/python3.5/site-packages/pip/wheel.py", line 347, in move_wheel_files
    assert info_dir, "%s .dist-info directory not found" % req
AssertionError: pymor-master-latest==9999.9.rc0 .dist-info directory not found
```

Any ideas?

**Comment by renemilk** [comment]
Oh, and another thing we didn't consider yet: what about pull-request builds? These currently land in the master branch section, since there ```TRAVIS_BRANCH``` is set to master and I'm only using this to distinguish. Obviously that is not what we want. IMO we either skip deploying wheels in PR builds altogether, or they need to go into a dedicated subdir.

**Comment by renemilk** [comment]
> IMO we either skip deploying wheels in PR builds altogether, or they need to go into a dedicated subdir.

Opinions?

Also, we could use https://pymor.github.io/wheels/ as the dumping ground instead of wheels.pymor.org, thereby avoiding all the https setup stuff with github+custom subdomains.

**Pull request merged**
