### PR TITLE
Enforce PR label usage

### PR DESCRIPTION
**Pull request by renefritze**

### CODE REVIEW

**Comment by renefritze** [comment]
We should get an error message now that I removed the `pr:new-feature` label

**Comment by sdrave** [comment]
Nice! Although the custom error message does not seem to appear anywhere. (Not important, I guess.)

**Comment by renefritze** [comment]
You have to open the log and scroll down. But I agree, since that action should never have a real and different error state it's not important.

**Comment by renefritze** [comment]
Currently stuck due to https://status.dev.azure.com/_event/195371070

**Pull request merged**
