### PR TITLE
fix incorrect docstring

### LINKED ISSUE #1541: Wrong type in docstring of `solve_lyap_dense`
As the title states, the type of `E` is said to be `Operator` in the first part of the docstring, whereas `NumPy array` would be the correct type.

### PR DESCRIPTION
**Pull request by artpelling**
fixes #1541.

### CODE REVIEW

**Comment by renefritze** [comment]
@artpelling can you please rebase this on main to get the CI problems resolved? Thanks!

**Comment by artpelling** [comment]
> @artpelling can you please rebase this on main to get the CI problems resolved? Thanks!

Done. Out of curiosity (I am a git noob), is there a best practice for rebasing? Can I achieve it without using the force?

**Comment by renefritze** [comment]
> > @artpelling can you please rebase this on main to get the CI problems resolved? Thanks!
> 
> Done. Out of curiosity (I am a git noob), is there a best practice for rebasing? Can I achieve it without using the force?

No. If the rebase isn't a fast-forward compared to the current state (both branches have changes) then force is required. 

Alternatively you could _merge_ main into your feature branch, this would require no force pushing, but you end up with a merge commit adding the changes from main. This we (or at least I) generally try to avoid for aesthetic preference in how the history looks.

**Comment by artpelling** [comment]
> > > @artpelling can you please rebase this on main to get the CI problems resolved? Thanks!
> > 
> > 
> > Done. Out of curiosity (I am a git noob), is there a best practice for rebasing? Can I achieve it without using the force?
> 
> No. If the rebase isn't a fast-forward compared to the current state (both branches have changes) then force is required.
> 
> Alternatively you could _merge_ main into your feature branch, this would require no force pushing, but you end up with a merge commit adding the changes from main. This we (or at least I) generally try to avoid for aesthetic preference in how the history looks.

Got it, thanks!

**Review by pmli — APPROVED** [review]

**Pull request merged**
