### PR TITLE
Tutorial 1 minor fixes

### PR DESCRIPTION
**Pull request by pmli**

### CODE REVIEW

**Comment by sdrave** [comment]
@renefritze please also take a look here. In the one build, we have again unusable hypothesis failures. In the other build, missing gcc is reported.

**Comment by renefritze** [comment]
That log is also stopping right in the middle of output from hypothesis/pytest. Trying to address this in #993 now

**Comment by sdrave** [comment]
@renefritze, do I need to rebase on master or is restarting the build enough?

**Comment by renefritze** [comment]
Rebase on master after #993 is merged.

**Pull request merged**
