### PR TITLE
Start testing against python 3.8

### PR DESCRIPTION
**Pull request by renefritze**

### CODE REVIEW

**Comment by renefritze** [comment]
Made note to re-enable pymess tests: #891

**Comment by renefritze** [comment]
The last remaining blocker seems to be an issue with ipyparallel: https://github.com/ipython/ipyparallel/issues/396

**Comment by renefritze** [comment]
Are there any reservations against merging this after CI clears?

**Comment by sdrave** [comment]
I think we should also open an issue for the ipyparallel tests. And maybe d32f62e  should be put into a separate PR? Apart from that I see no reason not to merge this PR. We should also add 3.8 to the supported Python versions?

**Comment by sdrave** [comment]
Sorry, didn't see that ipyparallel is covered by #891.

**Comment by renefritze** [comment]
I actually found some deeper problems while trying to find why the 3.8 jobs sometime hang indefinitely during the pytest reporting phase, so there's a bunch more changes incoming. 

> And maybe d32f62e should be put into a separate PR? 
Why though? I felt this was a trivial and obvious change that does not warrant a standalone branch. Esp. since there are no more changes like that necessary AFAICT.

**Comment by renefritze** [comment]
Great. Now that everything works, the friggin status reporting from the PR build broke.

**Pull request merged**
