### PR TITLE
Add favicon to pymor.org

### PR DESCRIPTION
**Pull request by pmli**

### CODE REVIEW

**Comment by sdrave** [comment]
Do you have a screenshot?

**Comment by pmli** [comment]
Here it is:

tab_with_favicon

**Comment by sdrave** [comment]
As I thought, this is quite small. What do you think about just taking the `M`? Surely would require some extra work to get rid of the upper-left bar of the y, but it would be almost square and include parts of 'py' and 'MOR'.

**Comment by pmli** [comment]
The 'y' and 'M' are separable by a vertical line, so it was straightforward to extract the 'M'. Here is how it looks like:

tab_M

**Comment by sdrave** [comment]
This is what I had in mind:

favicon

But maybe yours is better? Don't know.

**Comment by HenKlei** [comment]
This is what @sdrave's version would look like:

favicon_test

Personally, I prefer @pmli's version.

**Comment by sdrave** [comment]
> Personally, I prefer @pmli's version.

I agree. @pmli, shall we merge your version?

**Comment by pmli** [comment]
> @pmli, shall we merge your version?

Fine with me.

**Comment by sdrave** [comment]
We should also add the favicon to the documentation.

**Pull request merged**
