### PR TITLE
Introduce 'bindings' package

### PR DESCRIPTION
**Pull request by sdrave**
This pull request introduces a new 'pymor.bindings' package which is supposed to contain all glue code to interface with external high-dimensional solver libraries. These can be PDE solvers (fenics, dealii, ngsolve, dune, etc.), as well as equation solvers (scipy, pyamg, slycot, pymess, etc.)

In general, code in 'pymor.bindings' has the purpose of either translating pyMOR objects (`Operators`, `VectorArrays`, `Discretizations`) to objects understood by the external library (e.g. convert a linear Operator to a matrix of appropriate format), or to wrap objects of the external library to comply to pyMOR's interfaces (e.g. to integrate an external PDE solver with pyMOR).

@ftalbrecht, @pmli, please take a look if you are ok with the new design. As we have discussed in #291,
the glue code for slycot and pymess would go into `solve_lyap` methods located in `pymor.bindings.slycot` and `pymor.bindings.pymess` modules.

### CODE REVIEW

**Comment by ftalbrecht** [comment]
LGTM. Would be nice to see how DUNE integrates into this...

**Comment by sdrave** [comment]
@ftalbrecht, what do you mean by that?

**Comment by ftalbrecht** [comment]
That I cannot say more than LGTM until I have written bindings for dune-gdt, which should happen within the new weeks, hopefully...

**Comment by sdrave** [comment]
Ok, but what could be specific about dune that would make placing bindings in `pymor.bindings` inappropriate?

**Pull request merged**
