### PR TITLE
Handle matplotlib.cm.get_cmap deprecation

### LINKED ISSUE #2141: Matplotlib get_cmap deprecation warning
Some tests raise deprecation warnings about `matplotlib.cm.get_cmap`. The usage of `get_cmap` should be updated and we should decide on the oldest supported matplotlib version.

---

Below are examples using matplotlib from version 3.7.2 to 3.4.3 (released on August 12, 2021, compared to NumPy 1.20.3 released on May 10, 2021).

Summary:

- `matplotlib.colormaps[name]` or `matplotlib.colormaps.get_cmap(obj)` should be used since version 3.7
- version 3.6 also supports the above
- version 3.5 supports the first but not the second
- version 3.4 supports neither, and `matplotlib.cm` has to be imported directly

---

matplotlib 3.7.2:

```pycon
>>> import matplotlib as mpl
>>> mpl.cm.get_cmap('viridis')
<stdin>:1: MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed two minor releases later. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap(obj)`` instead.
<matplotlib.colors.ListedColormap object at 0x7fcec9a3c550>
>>> mpl.colormaps['viridis']
<matplotlib.colors.ListedColormap object at 0x7fcec9afe260>
>>> mpl.colormaps.get_cmap('viridis')
<matplotlib.colors.ListedColormap object at 0x7fce955e2cb0>
```

matplotlib 3.6.3:

```pycon
>>> import matplotlib as mpl
>>> mpl.cm.get_cmap('viridis')
<matplotlib.colors.ListedColormap object at 0x7f763d6d2230>
>>> mpl.colormaps['viridis']
<matplotlib.colors.ListedColormap object at 0x7f763d7af040>
>>> mpl.colormaps.get_cmap('viridis')
<matplotlib.colors.ListedColormap object at 0x7f7609134910>
```

matplotlib 3.5.3:

```pycon
>>> import matplotlib as mpl
>>> mpl.cm.get_cmap('viridis')
<matplotlib.colors.ListedColormap object at 0x7f0131d12230>
>>> mpl.colormaps['viridis']
<matplotlib.colors.ListedColormap object at 0x7f016638b760>
>>> mpl.colormaps.get_cmap('viridis')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'ColormapRegistry' object has no attribute 'get_cmap'
```

matplotlib 3.4.3:

```pycon
>>> import matplotlib as mpl
>>> mpl.cm.get_cmap('viridis')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'matplotlib' has no attribute 'cm'
>>> mpl.colormaps['viridis']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'matplotlib' has no attribute 'colormaps'. Did you mean: 'colors'?
>>> mpl.colormaps.get_cmap('viridis')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'matplotlib' has no attribute 'colormaps'. Did you mean: 'colors'?
>>> from matplotlib import cm
>>> cm.get_cmap('viridis')
<matplotlib.colors.ListedColormap object at 0x7f19547734f0>
```

### PR DESCRIPTION
**Pull request by sdrave**
Fixes  #2141.

### CODE REVIEW

**Review by pmli — COMMENTED** [review]
Should we also specify the oldest supported matplotlib version in `requirements-ci-oldest-pins.in`? Currently, `requirements-ci-oldest.txt` has `matplotlib==3.7.2`.

**Comment by sdrave** [comment]
> Should we also specify the oldest supported matplotlib version in `requirements-ci-oldest-pins.in`? Currently, `requirements-ci-oldest.txt` has `matplotlib==3.7.2`.

Probably a good idea.

**Comment by pmli** [comment]
Does `matplotlib==3.4.3` sound reasonable?

**Comment by sdrave** [comment]
> Does `matplotlib==3.4.3` sound reasonable?

Turns out that Qt6 support was only introduced in matplotlib 3.5. As I want to avoid having to use pyside2 in the oldest image again, I opted to require 3.5 as the minimal matplotlib version. This also allows us to get rid of the import workaround.

**Comment by sdrave** [comment]
> > Does `matplotlib==3.4.3` sound reasonable?
> 
> Turns out that Qt6 support was only introduced in matplotlib 3.5. As I want to avoid having to use pyside2 in the oldest image again, I opted to require 3.5 as the minimal matplotlib version. This also allows us to get rid of the import workaround.

Well, so the Qt6 support in matplotlib 3.5 is incompatible with pyside6>=6.4.3, which is seems to be needed in CI to avoid issues with conda builds. As a consequence I have bumped the pin again to matplotlib==3.6.2, which is the oldest matplotlib that works with the newer pyside. However, I left the matplotlib>=3.5.0 pin as that version also should work fine an pinning an even newer version feels too restrictive.

**Pull request merged**
