### PR TITLE
Add NumpyGenericOperator.apply_adjoint

### PR DESCRIPTION
**Pull request by pmli**
See #303

### CODE REVIEW

**Comment by sdrave** [comment]
LGTM. While we are at it, we might want to hook up a fixture in `pymortests.fixtures.operators`.

**Comment by pmli** [comment]
Should there also be `source_product` and `range_product`?

**Comment by sdrave** [comment]
Oh, I totally overlooked that. Yes, since it's part of the interface, it would better to add `source_product` and `range_product` parameters.

**Comment by pmli** [comment]
I have trouble with pickling functions...

**Comment by sdrave** [comment]
@pmli, we have two tests for pickling: one that allows our hack to make pickling of arbitrary functions possible and one that tests pickling without this hack. The second variant was applied in `pymortests.operators` to all possible operators. However, lambdas are not picklable, so this test had to fail. I have improved the pickling tests so that everything should be fine now.

**Comment by sdrave** [comment]
@pmli, feel free to merge ...

**Pull request merged**
