### PR TITLE
Use RuleTables for algorithms on Operator hierarchies 

### PR DESCRIPTION
**Pull request by sdrave**
This addresses #274 and #262. Documentation is still missing, but the overall concept is there. @pymor/pymor-devs, @andreasbuhr, please take a close look if you like the design. (Note that it is still impossible to dynamically add rules to a RuleTable, etc.)

### CODE REVIEW

**Comment by ftalbrecht** [comment]
One trivial change that came out of our discussion: the `native` pygments colorscheme does not work well with light backgrounds. The following alternatives seem to work on light backgrounds (perhaps `default` would be a reasonable default):
```
['default',
 'emacs',
 'friendly',
 'colorful',
 'autumn',
 'manni',                                                                                                                     
 'perldoc',
 'pastie',
 'borland',
 'bw',
 'vs',
 'tango',
 'xcode',
 'igor',
 'algol',
 'algol_nu',
 'arduino',
 'rainbow_dash',
 'abap']
```

**Comment by sdrave** [comment]
I have now added a bit of documentation and `RuleTables` can now be modified via `insert_rule` and `append_rule` methods. If everyone agrees that this is a good way to go, I would like to merge soon to master, so there is enough time for testing and improvement before the next release ... 

@pmli, if I haven't overlooked anything, there should not be a lot of consequences for the sys-mor branch, right?

**Comment by pmli** [comment]
@sdrave I merged sys-mor and rules branch, and when running the `heat.py` demo, I got the following error
```
Traceback (most recent call last):
  File "./heat.py", line 91, in <module>
    rom_bt, _, _ = bt(lti, r, tol=1e-5)
  File "/home/mp/Documents/mpi/codes/pymor/src/pymor/reductors/bt.py", line 100, in bt
    rom, rc, _ = reduce_generic_pg(discretization, V, W, use_default=['E'])
  File "/home/mp/Documents/mpi/codes/pymor/src/pymor/reductors/basic.py", line 210, in reduce_generic_pg
    for k, op in discretization.operators.items()}
  File "/home/mp/Documents/mpi/codes/pymor/src/pymor/reductors/basic.py", line 210, in <dictcomp>
    for k, op in discretization.operators.items()}
AttributeError: 'NumpyMatrixOperator' object has no attribute 'projected'
```

**Comment by sdrave** [comment]
Hi @pmli, `reduce_generic_pg` still needed updating (`op.projected(...)` -> `project(op, ...)`). I made the changes in the `sys-mor-with-rules` branch ...

**Comment by pmli** [comment]
Demos and notebooks are working now :+1:

**Pull request merged**
