### PR TITLE
Biorthogonal Gram Schmidt

### PR DESCRIPTION
**Pull request by pmli**
As in #334, but for the master branch,

### CODE REVIEW

**Comment by sdrave** [comment]
Hi @pmli, could you maybe add some tests for `gram_schmidt_biorth` in spirit of the tests I have just added to `pymortests.algorithms.gram_schmidt`?

**Comment by pmli** [comment]
Ok, no problem. Could you tell me how to generate two (different and random) vectorarrays from the same space and of the same length? Is there already a fixture for that?

**Comment by sdrave** [comment]
Unfortunately no, there is no fixture. I guess the easiest thing would be to take a single array and split it into two.

**Comment by sdrave** [comment]
I have just had a look at the test failures. These all come from fenics VectorArrays and would pass when `rtol` is increased to `1e-8`. I have converted one of the arrays to a `NumpyVectorArray` which you can load  [here](https://github.com/pymor/pymor/files/664652/fail.zip). Maybe you can have a look if this is expected and we can simply raise the tolerance, or if the algorithm should be improved.

**Comment by pmli** [comment]
Thanks! I've changed the `rtol`. Now it depends on condition numbers of computed biorthogonal vectorarrays, since I guess this is what causes most numerical errors when computing `A1.lincomb(U1.dot(A2))`. If it fails again for fenics vectorarrays, I propose to increase `rtol` more.

My reason for increasing `rtol`, instead of improving the algorithm, is that biorthogonalization is not well-posed for every pair of subspaces. The assumption is that `U1.dot(U2)` (or `p.apply2(U2, U1)`) is invertible.

**Comment by sdrave** [comment]
An interesting question would be, what accuracy can be expected for the corresponding check for `gram_schmidt`. @andreasbuhr, @pmli, do you have any idea?

**Comment by sdrave** [comment]
No one seem to know for sure what accuracy to expect. For now, I will merge as is ...

**Pull request merged**
