### PR TITLE
Lyapunov and Riccati equation solvers as free functions

### PR DESCRIPTION
**Pull request by pmli**

### CODE REVIEW

**Comment by pmli** [comment]
Fixes #476.

I've decided to remove `solve_lyap` and replace it with `solve_lyap_lrcf` and `solve_lyap_dense`. Conceivably, there might be other solvers added which do not return a low-rank Cholesky factor or a dense matrix, but, e.g., a low-rank tensor format.
Similarly, instead of `solve_ricc`, there is now `solve_ricc_lrcf` and `solve_pos_ricc_lrcf` for (normal) Riccati equations and "positive" Riccati equations. In the future, there might also be a solver for "indefinite" Riccati equations.

**Comment by pmli** [comment]
I've removed `np.matrix` in `bindings.pymess`. The tests run locally, so it seems to work. Also, the travis log files should be shorter now (no more `PendingDeprecationWarning` about `np.matrix`).

**Comment by sdrave** [comment]
Yeah, it really makes me happy that we finally will be able to live in a world without numpy.matrix.

**Comment by pmli** [comment]
@sdrave One thing I forgot to explain is why some tests in `pymortests/riccati.py` are skipped. The thing is that `pymess.lrnm` does not support the `S` operator, but this could be fixed if there would be a "operator + low-rank update" operator (`S` can be moved to the `A` part). Is it ok to open a separate issue/PR about such operator?

**Comment by pmli** [comment]
> - I noticed that you don't use pyMOR's defaults mechanism for solver_options. I could change that in a separate PR after merging this.
> - From my POV it would make more sense to have B and C as VectorArrays for the low-rank methods? In particular, it would make it clearer what the comments with the small dimension mean.
> - algorithms.lyapunov.chol seems for like an internal wrapper for the dense backends when requiring a low-rank approximation. In particular, its inputs requires a NumPy array not an Operator or a VectorArray. Thus, maybe it would make more sense to call it _chol instead of chol.

This all makes sense. I can work on it here.

**Comment by sdrave** [comment]
> @sdrave One thing I forgot to explain is why some tests in pymortests/riccati.py are skipped. The thing is that pymess.lrnm does not support the S operator, but this could be fixed if there would be a "operator + low-rank update" operator (S can be moved to the A part). Is it ok to open a separate issue/PR about such operator?

I guess it's absolutely ok if not every solver satisfies the entire interface. However, if I activate the skipped tests, I get some nasty internal mess errors. It would better to catch this case in the pymess bindings.

**Comment by pmli** [comment]
> I guess it's absolutely ok if not every solver satisfies the entire interface. However, if I activate the skipped tests, I get some nasty internal mess errors. It would better to catch this case in the pymess bindings.

What I got was another example of a "maximum recursion" error, when looking far enough in the traceback.
How would you suggest to catch the `S` case in pymess bindings? Raise `NotImplementedError`?

**Comment by sdrave** [comment]
> How would you suggest to catch the S case in pymess bindings? Raise NotImplementedError?

Yes.

**Comment by pmli** [comment]
Now B, C, S are vector arrays and R a NumPy array for low-rank methods, and everything is a NumPy array for dense methods.

Another thing I forgot to mention, which would be good for future reference: the reason for changing `slycot` to `slycot-bartels-stewart`, as a method name for Lyapunov equation solvers, is that I also tried adding solvers based on the Hammarling method from `slycot`, but found a strange issue with `slycot.sg03bd` (it would raise an error saying that the QZ decomposiiton algorithm didn't converge when it should work).

**Comment by sdrave** [comment]
@pmli, I have just made some changes regarding your use of `defaults` in analogy to the use of defaults for linear solvers. Please double-check if everything makes sense.

**Comment by pmli** [comment]
@sdrave ok, nice. I made some improvements in `bindings.pymess` (more options and moving paratype option to `lradi_solver_options`).

**Comment by sdrave** [comment]
LGTM

**Pull request merged**
