### PR TITLE
Try on binder

### PR DESCRIPTION
**Pull request by renefritze**
This PR adds a sphinx extension that exposes a new directive to include a binder badge link to a branch in the pymor/docs repo where the generated tutorial notebooks live. 

[Example](https://docs.pymor.org/try-on-binder/tutorial_basis_generation.html) 

Open for suggestions on badge link positioning and text.

### CODE REVIEW

**Comment by renefritze** [comment]
Have a look @pymor/all 
screenshot-docs pymor org-2020 11 25-13_10_33

Fixes for the v-align of the badge welcome.

TODO:

 - [ ] notebooks are read-only on binder 
 - [ ] outputs don't preload
 - [x] fix typo in note: make -> may

Integrating the download notebook links I will defer.

**Comment by sdrave** [comment]
> [Have a look](https://docs.pymor.org/try-on-binder/tutorial_builtin_discretizer.html) @pymor/all

Very nice! Maybe remove the 'Click here' as there is already the launch button?

**Comment by renefritze** [comment]
> > [Have a look](https://docs.pymor.org/try-on-binder/tutorial_builtin_discretizer.html) @pymor/all
> 
> Very nice! Maybe remove the 'Click here' as there is already the launch button?

I've intentionally made both a link in case people do not think to click the badge

**Comment by renefritze** [comment]
With the last commit the remaining issues are fixed and this is now ready to merge.

**Pull request merged**
