### PR TITLE
Add notion of output to ModelInterface

### PR DESCRIPTION
**Pull request by sdrave**
This implements the proposal discussed in #698.

Note that `output` cannot yet be implemented for `LTIModel` as we do not have settled yet on the right notion of `input` in `ModelInterface`. There might be another issue with `SecondOrderSystem`: By definition, `output` gets a `VectorArray` from `solution_space`, which in case of `SecondOrderSystem` does not contain the time derivative of the state, so either `output` would need to compute the time from the state trajectory, `solution_space` would have to be changed, or the definition of `output` would have to be relaxed. Any thoughts, @pmli?

### CODE REVIEW

**Comment by pmli** [comment]
Yes, right. I guess there is also the issue of the initial condition for `SecondOrderModel`, which should contain both initial position and velocity. Does this mean `solution_space` should contain both or should there be a special `initial_condition_space` (or `state_space`)?

For time-delay systems, the initial condition should be `x(t)` for `t` in some time interval, but I guess it is not feasible for `solve` to return something of that form.

**Comment by sdrave** [comment]
Well, going by the current definitions in `ModelInterface`, the following conditions should be met:

1. The result of `solve` should be a `VectorArray` of `solution_space` for the solution return value and a `VectorArray` of `output_space` for the output return value.
2. The `output` method should map `VectorArrays` from `solution_space` together with a parameter (and the input ...) to corresponding `output_space` `VectorArrays`.
3. `m.output(m.solve(mu))` should be the same as `m.solve(mu, return_output=True, return_solution=False)`. (Note that the latter could always be used as implementation of `output` without looking at the given `VectorArrays`. Obviously, there is an implicit assumption that `output` does less work to obtain the `output` then `solve`.)

I am still not completely sure if this is the best common ground for all `Models` in pyMOR. In particular, there are `Models` without a state space for which `output` makes not much sense (however, I guess projection based methods will be the main focus for pyMOR for the foreseeable future). Then there are cases like `SecondOrderSystem` where it is maybe not that clear how to define `solution_space` and/or `output`.

**Comment by pmli** [comment]
Right, and for linear delay systems, the output could be `y(t) = C1 x(t) + C2 x(t - tau)` (although it's not possible right now in `LinearDelayModel`), which also makes it more complicated.

It is still not clear to me where would the `output` method be used. Does it appear in some RB methods? Are there situations where a `VectorArray` from `solution_space` doesn't come from a `solve` method?

**Comment by sdrave** [comment]
Superseded by #750.

**Pull request closed without merging**
