### PR TITLE
Added functionality to collapse long lists in the api reference

### PR DESCRIPTION
**Pull request by HenKlei**
I did some jQuery hacking and this is probably what @artpelling was looking for, right?

### CODE REVIEW

**Comment by artpelling** [comment]
Thanks! This is already a big improvement :)

**Review by artpelling — APPROVED** [review]

**Review by sdrave — COMMENTED** [review]
Very nice!

The only issue I have with that is that my mouse cursor, when hovering over the collapse/uncollapse triangle get this 'text box editing' shape instead of the 'clickable link' shape. @HenKlei, would it easily be possible to change that?

**Comment by HenKlei** [comment]
> Very nice!
> 
> The only issue I have with that is that my mouse cursor, when hovering over the collapse/uncollapse triangle get this 'text box editing' shape instead of the 'clickable link' shape. @HenKlei, would it easily be possible to change that?

I thought the same and was hoping that nobody notices :-D Will take a look.

**Comment by sdrave** [comment]
> > Very nice!
> > The only issue I have with that is that my mouse cursor, when hovering over the collapse/uncollapse triangle get this 'text box editing' shape instead of the 'clickable link' shape. @HenKlei, would it easily be possible to change that?
> 
> I thought the same and was hoping that nobody notices :-D Will take a look.

Cool, much smoother now!

**Review by sdrave — APPROVED** [review]

**Pull request merged**
