### PR TITLE
remove unused imports

### PR DESCRIPTION
**Pull request by artpelling**
this PR removes unused imports and fixes some more flake8 errors.

### CODE REVIEW

**Comment by pmli** [comment]
Thanks for the PR. It looks like there are a few more unused imports if you want to deal with those:

```bash
$ flake8 src | grep F401
src/pymortests/solver.py:11:1: F401 'pymor.core.config.config' imported but unused
src/pymor/discretizers/builtin/list.py:8:1: F401 'pymor.operators.constructions.VectorFunctional' imported but unused
src/pymor/discretizers/builtin/list.py:8:1: F401 'pymor.operators.constructions.VectorOperator' imported but unused
src/pymor/scripts/pymor_demo.py:10:1: F401 'pprint' imported but unused
src/pymor/scripts/pymor_demo.py:15:1: F401 'functools' imported but unused
src/pymor/analyticalproblems/burgers.py:5:1: F401 'numpy as np' imported but unused
src/pymor/operators/numpy.py:25:1: F401 'pymor.core.config.config' imported but unused
src/pymor/tools/floatcmp.py:5:1: F401 'operator' imported but unused
src/pymor/tools/floatcmp.py:6:1: F401 'warnings' imported but unused
```

**Comment by renefritze** [comment]
> this PR removes two instances of unused imports.

Somewhat related: did you see the `pre-commit` [section](https://docs.pymor.org/main/developer_docs.html#pre-commit-hooks) in the developers documentation yet?

**Comment by artpelling** [comment]
> > this PR removes two instances of unused imports.
> 
> Somewhat related: did you see the `pre-commit` [section](https://docs.pymor.org/main/developer_docs.html#pre-commit-hooks) in the developers documentation yet?

Yes, I have that up and running :)

**Comment by artpelling** [comment]
Ah great, I was trying to achieve that myself.. Will fix those as well

**Comment by artpelling** [comment]
There also are a lot of `D205 1 blank line required between summary line and description` errors. Should I fix those as well?

**Comment by renefritze** [comment]
> There also are a lot of `D205 1 blank line required between summary line and description` errors. Should I fix those as well?

If you want to, sure. That would be great.

**Comment by artpelling** [comment]
> > There also are a lot of `D205 1 blank line required between summary line and description` errors. Should I fix those as well?
> 
> If you want to, sure. That would be great.

I have pushed further fixes. I was overhasty when it comes to the D205 errors, because all the summary lines would have to be reworded. Whenever there is a D205, the summary line exceeds the maximum length for docstrings of 100, so a linebreak was inserted.
All remaining flake8 errors I could find are somehow related to the docstrings. We should consider ignoring those, increasing the max-length for docstrings or in fact reword the summaty lines.

**Review by renefritze — APPROVED** [review]

**Comment by renefritze** [comment]
> My suggestion would be to open an issue about the docstring formats and merge this PR in its current state.

Sounds good to me. Thanks!

**Pull request merged**
