### PR TITLE
Jupyter sphinx

### PR DESCRIPTION
**Pull request by renefritze**
As discussed in the last dev meeting I've looked into switching from nbplots to jupyter-sphinx.
It worked so well that I got greedy and also switched to the pythreejs backend, which has issues still: https://gh-docs.pymor.org/jupyter-sphinx/tutorial01.html

During the meeting we had identified two issues with this plugin:
 1. The downloadable notebook is missing widget outputs/state
 1. The downloadable notebook is missing text cells

Turns out 1. isn't actually true. And for 2. there's already [an issue](https://github.com/jupyter/jupyter-sphinx/issues/94).

Assuming I fix the threejs issue (which I have to anyways), I think the switch is clearly the way forward. 

@ftalbrecht That issue is probably the same you mentioned in #801  just now.

### CODE REVIEW

**Comment by renefritze** [comment]
The inclusion of https://github.com/pymor/pymor/pull/968/commits/77a45ae2d065d2f9bcc2932a42b2a239bc3ec3ba and https://github.com/pymor/pymor/pull/968/commits/7fb4778d4422e8101b55ccc1eeb327c7e65610d6 depends on https://github.com/vidartf/ipyscales/issues/24 

My part in https://github.com/pymor/pymor/issues/929 already uses jupyter_sphinx

**Comment by sdrave** [comment]
BTW, I am seeing a black output window in https://gh-docs.pymor.org/jupyter-sphinx/tutorial01.html on Firefox 77.0.1 with nvidia drivers. If we can't reliably fix this issue, I would disable the webgl output at least for the documentation for now. - Otherwise the page looks great!

**Comment by renefritze** [comment]
Yeah, I know about the squares. I think you missed the discussion in the current load behaviour last week. [See also](https://github.com/jupyter-widgets/pythreejs/issues/327)

**Comment by renefritze** [comment]
I'm excluding the ipyscales change for now

**Comment by renefritze** [comment]
@sdrave  please check https://gh-docs.pymor.org/safari-check/tutorial01.html wrt the black boxes

**Comment by sdrave** [comment]
Seems to work. What did you change? - I am somewhat concerned about stability. Viewing the documentation should also work on a tablet and so on ..

**Comment by renefritze** [comment]
4c4de773cfa1a280c0a713d51ca44d35c0142b7e that's it.

**Comment by renefritze** [comment]
Screenshot_2020-07-01-12-51-23-817_com android chrome

Mobile looks good.

**Comment by renefritze** [comment]
With the last [layout fix ](https://gh-docs.pymor.org/jupyter-sphinx/getting_started.html) (look at the triple plot)  I'm now ready to merge this.

**Comment by sdrave** [comment]
Also seems to work on my phone. Nevertheless I am not completely sure if we should use the webgl output in the docs for this release. If the docs don't render properly, this will give a pretty bad first impression. There are also more tutorials to come which may trigger new issues.

I would feel safer, if we keep the matplotlib backend for the docs in this release and then switch over for the next.

What did you do to get rid of the black boxes?

**Comment by renefritze** [comment]
> Seems to work. What did you change? - I am somewhat concerned about stability. Viewing the documentation should also work on a tablet and so on ..



> [4c4de77](https://github.com/pymor/pymor/commit/4c4de773cfa1a280c0a713d51ca44d35c0142b7e) that's it.

**Comment by renefritze** [comment]
> There are also more tutorials to come which may trigger new issues.

If anybody wants to show vectorarrays with `len > 1`, then yes. Otherwise, don't think so.

> I would feel safer, if we keep the matplotlib backend for the docs in this release and then switch over for the next.

Unless above becomes true, I'd be OK with the webgl plots in docs. I also don't think it's very important to have them in docs right now, so I'm also OK with switching in the release branch. If we follow your reasoning here though, we'd also not switch to the new theme for the release, correct?

**Comment by renefritze** [comment]
@TiKeil what you noticed with the two `visualize` calls only worked becaue the visualizer explicitly called `display` (which it shouldn't) https://github.com/pymor/pymor/pull/968/commits/30dc90deb2501c5adf90258eb35c1fe187d7b2fc

**Comment by renefritze** [comment]
I've also tweaked the layouting some so color bars and plots are kept together during row overflow. Colorbars are also now tighter with the plot. 
https://gh-docs.pymor.org/jupyter-sphinx/tutorial01.html (make sure to clear cache wit reload)

**Comment by ftalbrecht** [comment]
This is probably not related, but I noticed the following lines in the
RB.png demo:

```python
import os
print(os.getcwd())
```

I guess they make sense for debugging, but are those supposed to be there?

**Comment by sdrave** [comment]
>  >  There are also more tutorials to come which may trigger new issues.

> If anybody wants to show vectorarrays with len > 1, then yes. Otherwise, don't think so.

This is something I probably want to do. One of the tutorials will be about building a reduced basis, and it makes sense to visualize it.

>  >  I would feel safer, if we keep the matplotlib backend for the docs in this release and then switch over for the next.

> Unless above becomes true, I'd be OK with the webgl plots in docs. I also don't think it's very important to have them in docs right now, so I'm also OK with switching in the release branch. 

Ok, then let's not switch for the release.

> If we follow your reasoning here though, we'd also not switch to the new theme for the release, correct?

I think this is different: we can easily verify that the new theme works sufficiently well before the release. We cannot verify so easily if  the webgl stuffs will work reliably on all user clients.

**Comment by renefritze** [comment]
> Ok, then let's not switch for the release.

I'm sure you meant lets switch, right?

> we can easily verify 

If you can verify the one thing you can verify the other thing, no? You'll have to look at a bunch of browsers on at least 3 platforms anyhow.

**Comment by sdrave** [comment]
>  >  Ok, then let's not switch for the release.

> I'm sure you meant lets switch, right?

Yes.


>    we can easily verify

> If you can verify the one thing you can verify the other thing, no? You'll have to look at a bunch of browsers on at least 3 platforms anyhow.

I would have more trust in modern browsers to halfway accurately render some static html with a bit of css an javascript compared to them rendering webgl properly. For the latter, one would also have to check different OSs with different GL drivers.

**Comment by renefritze** [comment]
> I would have more trust in modern browsers to halfway accurately render some static html with a bit of css an javascript compared to them rendering webgl properly. 

Why though? The Problems we're having with the black boxes isn't some quirk in rendering webgl, but a bug in (py)threejs. Webgl 1 is also much older for example than css 3 which the bootstrap base in the material theme uses. So it can't be time to implement it properly. 

> For the latter, one would also have to check different OSs with different GL drivers.

I think you're setting yourself up with a high, and unrealistic, workload there.

**Comment by renefritze** [comment]
> This is probably not related, but I noticed the following lines in the RB.png demo: ```python import os print(os.getcwd()) ``` I guess they make sense for debugging, but are those supposed to be there?

Nope, they are not. Good catch, thanks!

Aside from the tangentially related discussion, this is now good to merge.

**Comment by sdrave** [comment]
>   > For the latter, one would also have to check different OSs with different GL drivers.

> I think you're setting yourself up with a high, and unrealistic, workload there.

My idea was something like: let people use it some more in the notebook (it's the default now) and if we don't get any further complaints, it's probably safe enough to also use it for the docs. - However, if you have confidence in the code, I'm ok with using it for the docs as well. However, as I said, time series should work as well.

**Pull request merged**
