### PR TITLE
Switch to K3D-based visualizations in Jupyter environments

### PR DESCRIPTION
**Pull request by renefritze**
This PR significantly improves the [K3D](https://k3d-jupyter.org/)-based visualizer for our builtin discretizations and makes it the default backend for documentation builds. It will also automatically be the default backend in Jupyter notebooks as soon as https://github.com/K3D-tools/K3D-jupyter/pull/424 is released.

The old, currently broken pythreejs-based visualizer is removed.

(new comment by @sdrave)

### CODE REVIEW

**Comment by renefritze** [comment]
K3D display works now in principal: https://docs.pymor.org/new-k3d-vis/tutorial_builtin_discretizer.html

Some obvious problems remain:
1. quadrilateral element display is broken
2. the widget display scrolls over the top bar 
3. general layouting of the widget output

Non-obvious:
1. No time-dep/multiple param stuff works yet

**Comment by renefritze** [comment]
> K3D display works now in principal: https://docs.pymor.org/new-k3d-vis/tutorial_builtin_discretizer.html
> 
> Some obvious problems remain:
> 
> 1. quadrilateral element display is broken

Fixed

> 2. the widget display scrolls over the top bar

Fixed by @HenKlei 

> 3. general layouting of the widget output

unclear how to fix

> 
> Non-obvious:
> 
> 1. No time-dep/multiple param stuff works yet

Fixed. (at least in live jupyter)

New/Remaining Problems:

1. https://docs.pymor.org/new-k3d-vis/tutorial_optimization.html vs https://docs.pymor.org/2022-2-0/tutorial_optimization.html
2. JSLink (needed for multi-plot time/camera linking) does not seem to translate to sphinx html, although ipywidgets says it should
3. Colorbar/data scaling + multi legend args are currently ignored still

**Comment by sdrave** [comment]
@pymor/all, I believe this is now ready to be merged. Please take a look at the [tutorials](https://docs.pymor.org/new-k3d-vis/tutorials.html), and see if everything works with your browser setup. In particular, I could not test Safari @TiKeil.

**Comment by pmli** [comment]
The plots work for me. Some comments:

- It would be nice to also have the x/y/z axes (particularly for the plot in the NN tutorial, which has an almost flat surface).
- A "home" button would be good, to return the plot to the original state after rotating it.
- The speed slider is again in the opposite direction (e.g., in the "Building a Reduced Basis" tutorial).

**Pull request merged**
