### PR TITLE
Remove code for older slycot

### LINKED ISSUE #1734: Add `DeprecationWarning` for slycot < 0.4.0
Related to #1689, we should deprecate `slycot` < `0.4.0` in the future.

### PR DESCRIPTION
**Pull request by pmli**
Closes #1734.

### CODE REVIEW

**Comment by pmli** [comment]
@sdrave The oldest `slycot` version is already set to 0.5.4 in [`requirements-ci-oldest-pins.in`](https://github.com/pymor/pymor/blob/5fdb7cfac8cf1a8c985bc3ea9c783005df370531/requirements-ci-oldest-pins.in#L7). Any idea why "vanilla oldest" is still installing version 0.4.0?

**Comment by sdrave** [comment]
> @sdrave The oldest `slycot` version is already set to 0.5.4 in [`requirements-ci-oldest-pins.in`](https://github.com/pymor/pymor/blob/5fdb7cfac8cf1a8c985bc3ea9c783005df370531/requirements-ci-oldest-pins.in#L7). Any idea why "vanilla oldest" is still installing version 0.4.0?

See [here](https://github.com/pymor/pymor/blob/5fdb7cfac8cf1a8c985bc3ea9c783005df370531/docker/Dockerfile.ci-oldest#L24). I'm not quite remember, why I picked 0.4.0. Might be that it works the same with 0.5.4 ...

**Comment by pmli** [comment]
> > @sdrave The oldest `slycot` version is already set to 0.5.4 in [`requirements-ci-oldest-pins.in`](https://github.com/pymor/pymor/blob/5fdb7cfac8cf1a8c985bc3ea9c783005df370531/requirements-ci-oldest-pins.in#L7). Any idea why "vanilla oldest" is still installing version 0.4.0?
> 
> See [here](https://github.com/pymor/pymor/blob/5fdb7cfac8cf1a8c985bc3ea9c783005df370531/docker/Dockerfile.ci-oldest#L24). I'm not quite remember, why I picked 0.4.0. Might be that it works the same with 0.5.4 ...

Great, thanks! I was wondering for a long time how to install slycot with different NumPy versions... I'll try to upgrade it to 0.5.4 (unless somebody finds a reason to support 0.4.0).

**Comment by pmli** [comment]
I guess it is necessary to push the new image, but the image tag depends on `requirements-ci-oldest.txt`, which is unchanged. @sdrave what do you suggest?

**Comment by sdrave** [comment]
Kind of a hack, but you could just add a comment line to `requirements-ci-oldest.txt` to change the hash, I guess.

**Review by sdrave — APPROVED** [review]

**Pull request merged**
