### PR TITLE
MPL visualisation: fix 1D + animate series

### PR DESCRIPTION
**Pull request by renefritze**
This PR combines #1009 and #966 and fixes the remaining phantom draw issue. 
It also sets the backend for documentation vis to `MPL`.

### CODE REVIEW

**Comment by renefritze** [comment]
@HenKlei could you look this over again please? It's not unlikely I messed up some functionality you intended.

**Comment by renefritze** [comment]
2D: [Binder](https://mybinder.org/v2/gh/pymor/pymor/fix-1D-matplotlib_with_anim?filepath=test_visualization.ipynb)
1D: [Binder](https://mybinder.org/v2/gh/pymor/pymor/fix-1D-matplotlib_with_anim?filepath=elliptic+oned.ipynb)

**Comment by renefritze** [comment]
I've switched to the standard "inline" backend for MPL since that produces a much more compact presentation.
Synchronization of different animations is not straight forward at this point. 
The figures need a global enumeration/unique ID instead of the local sequence they have now. Or else weird stuff will happen.

**Comment by HenKlei** [comment]
`separate_plots=True` is not working anymore, was that intended?

**Comment by sdrave** [comment]
On https://docs.pymor.org/fix-1d-matplotlib-with-anim/ all visualizations which are not a time series seem to be missing.

**Comment by renefritze** [comment]
> `separate_plots=True` is not working anymore, was that intended?

Kinda. didn't pay special attention to it yet. I would also be OK not to include it in the release. 



> On https://docs.pymor.org/fix-1d-matplotlib-with-anim/ all visualizations which are not a time series seem to be missing.

Single plot usage is now fixed too.

I've also greatly reduced overall code duplication in the MPL stuff.

**Comment by renefritze** [comment]
I'm confused what `separate_plots` and `separate_axes` actually are supposed to do. Could you please clarify those a little @HenKlei?

**Comment by HenKlei** [comment]
> I'm confused what `separate_plots` and `separate_axes` actually are supposed to do. Could you please clarify those a little @HenKlei?

`separate_axes` is only relevant in the case where `separate_plots=True`. If separate plots are used, `separate_axes` is like `separate_colorbars` in the 2d case. It is relevant to be able to choose between those two options since the data you want to display might have different or same scales. For instance, in the case of a full-order solution and a reduced solution, you might pick `separate_axes=False`. However, if you want to display a reduced solution and the error, you should set `separate_axes=True` due to the different scales of your data.

I hope that makes it clear?

**Comment by renefritze** [comment]
I've disabled `separate_plot=True` with `len(U) > 1` and am now re-fixing the 2D plotting I broke. Should only take a couple of minutes :wink: 

@HenKlei There's another ANN failure in this PR: https://zivgitlab.uni-muenster.de/pymor/pymor/-/jobs/379842

**Comment by renefritze** [comment]
@sdrave maybe hold on a sec, doc building failed locally still

**Comment by renefritze** [comment]
Fixed.  20 is a couple, right?

**Comment by renefritze** [comment]
> But I suppose this is not so easy to fix?

You suppose correctly. I've opted to include code to synchronize the animations via prescribed event sources as MPL docs suggest, but alas that's not working as advertised.

**Pull request merged**
