### PR TITLE
Fix ComplexifiedVector.scal

### LINKED ISSUE #1655: Complex framework with FEnics vectors
**Describe the bug**
When a list of FEnics vectors is multiplied with a complex number, something goes wrong.

**To Reproduce**
MWE:
```
from pymordemos.parabolic_mor import discretize_fenics

# generate some array of FEnics vectors
fom = discretize_fenics()
U = fom.solve(fom.parameters)

# max value
print('max value: {}'.format(U.to_numpy().max()))

# max value when put to complex
print('max value after multiplication: {}'.format((U * 1j).to_numpy().max()))
```
Output:
```
max value: 24.97602803503706
max value after multiplication: 0j
```

**Expected behavior**
Should print the same maximum twice. But multiplication with 1j results in zero imaginary part.

**System information:**
```pyMOR Version 2021.2.0+495.g36842c002

Python 3.9.2 on Linux-5.10.0-15-amd64-x86_64-with-glibc2.31

External Packages
------------------------------
DEALII:      missing
DUNEGDT:     missing
FENICS:      2019.2.0.dev0
GL:          missing
IPYTHON:     missing
IPYWIDGETS:  missing
MATPLOTLIB:  missing
MESHIO:      missing
MPI:         3.0.3
NGSOLVE:     missing
NUMPY:       1.19.5
PYMESS:      missing
PYTEST:      7.1.1
PYTHREEJS:   missing
QT:          PyQt5 (Qt 5.15.2)
QTOPENGL:    present
SCIKIT_FEM:  6.0.0
SCIPY:       1.8.0
SCIPY_LSMR:  present
SLYCOT:      missing
SPHINX:      3.4.3
TORCH:       missing
TYPER:       0.4.1
VTKIO:       missing

Defaults
--------
See pymor.core.defaults.print_defaults.
```

### PR DESCRIPTION
**Pull request by sdrave**
Fixes #1655.

### CODE REVIEW

**Comment by sdrave** [comment]
The new test currently triggers a failure with the dealii bindings, which are not updated yet for complexified arrays.

**Comment by renefritze** [comment]
GItlab ci needs a restart once https://github.com/pymor/docker/pull/133 is merged

**Comment by sdrave** [comment]
@renefritze, there seems to be some problem with the [pyside version](https://zivgitlab.uni-muenster.de/pymor/pymor/-/jobs/1006588)?

**Comment by renefritze** [comment]
> @renefritze, there seems to be some problem with the [pyside version](https://zivgitlab.uni-muenster.de/pymor/pymor/-/jobs/1006588)?

I must;ve mixed up the docker update wrt constraints. I'll force push an update here when that's fixed.

**Comment by renefritze** [comment]
Tests seem to pass now @sdrave. This can me merged then, yes?

**Comment by renefritze** [comment]
[This](https://github.com/pymor/pymor/runs/7135298788?check_suite_focus=true#step:13:117) is  new :disappointed:

**Pull request merged**
