### PR TITLE
New Sphinx theme

### PR DESCRIPTION
**Pull request by renefritze**
Docs are already at: https://docs.pymor.org/sphinx-theme/generated/pymor.algorithms.html
Now waiting for rebuild after rebase on master

### CODE REVIEW

**Comment by renefritze** [comment]
Please have a look at the generated html up top, @pymor/pymor-devs while the PR failure is being addressed in #1020.

**Comment by renefritze** [comment]
I just saw layout fail at https://docs.pymor.org/sphinx-theme/tutorial_external_solver.html
and https://docs.pymor.org/sphinx-theme/tutorial_basis_generation.html

I think this warrants postponing to merge this PR until after the release.

**Comment by sdrave** [comment]
> I think this warrants postponing to merge this PR until after the release.

I agree.

**Comment by HenKlei** [comment]
If I see that correctly, it should be sufficient to set `display: inline-block` for the class `cell_output`.

**Comment by renefritze** [comment]
> If I see that correctly, it should be sufficient to set `display: inline-block` for the class `cell_output`.

Yepp, that did it. Thanks! 

Moving this back to 2020.1 then :grinning:

**Pull request merged**
