### PR TITLE
Developer docs

### PR DESCRIPTION
**Pull request by renefritze**

### CODE REVIEW

**Comment by renefritze** [comment]
I've committed a first draft with which topics I'll cover when I finish this later today/tomorrow morning. 
If anybody can think of something to be added lemme know.

**Comment by renefritze** [comment]
Writing this document turned out to be more work than anticipated, but I actually fixed a couple of misnomers and a serious CI along the way. So yay for that.
I'd appreciate some copy editing.

**Comment by pmli** [comment]
Thanks for working on this, @renefritze, it's looking good. Here are some ideas for things do add:

- code style guidelines (i.e., mention `flake8` and point to `setup.cfg`),
- what `src/pymor`, `src/pymortests`, and `src/pymordemos` are used for,
- the release checklist,
- explanation for issue/PR labels and milestones,
- how version numbering works,
- develop-oriented stuff from `README.md`.

**Comment by sdrave** [comment]
>     * develop-oriented stuff from `README.md`.

Yeah, I'd move 'Setting up an Environment for pyMOR Development' and 'Tests'. The document should be linked from README.md.

**Comment by renefritze** [comment]
I'll have to disable the link checker being mandatory to merge this. The failing link will only be introduced by the merge result of this PR.

**Pull request merged**
