### PR TITLE
update myst-nb config for new release

### PR DESCRIPTION
**Pull request by renefritze**

### CODE REVIEW

**Comment by renefritze** [comment]
There's in fact a problem with the gitlab->github bridge, which makes PR and (some) fork pushes not trigger builds, @pymor/all @pbuchfink
Trying to figure that this afternoon.

**Comment by renefritze** [comment]
> There's in fact a problem with the gitlab->github bridge, which makes PR and (some) fork pushes not trigger builds, @pymor/all @pbuchfink 

> ~Trying to figure that this afternoon.~

Figured it out already. The fix is not retroactive though, so if you have a PR stuck because of this there's two options:
1. new push 
2. goto settings->webhooks->gitlabbridge->"recent deliveries" and find the last synchronize/open event for your PR and then redeliver that hook

**Comment by renefritze** [comment]
Since this also updates to a new major version for myst-nb it would be nice if someone else had another eye on our [tutorials](https://docs.pymor.org/update-sphinx-config/index.html).

**Comment by sdrave** [comment]
> Since this also updates to a new major version for myst-nb it would be nice if someone else had another eye on our [tutorials](https://docs.pymor.org/update-sphinx-config/index.html).

LGTM.

**Pull request merged**
