### PR TITLE
[iosys] use caching in discretizations

### PR DESCRIPTION
**Pull request by sdrave**
This pull request replaces the hand-rolled caching in `InputOutputSystem` and subclasses by pyMOR's caching infrastructure. Not only is the code simplified, the change also makes it easier to ensure that the semantics of `ImmutableInterface` are fulfilled by these classes. (E.g., in the old implementation, the `_gramian` dict did not keep track of the `me_solver`. So if `compute_gramian` was called before calling `compue_sv_U_V`, the `me_solver` parameter of the latter method would have had no effect.)

Some remarks:
- I have defaulted the `cache_region` to `memory` to reproduce the old behavior.
- For the Hinf-norm computation `fpeak` is now returned along with the norm. If this is unwanted, alternatives would be to drop the `fpeak` value or have an optional parameter to the `norm` method to control if `fpeak` is returned or not.
- In the old implementation, `bode` always returned a copy of the cached result. The current implementatoin of `MemoryRegion` does not make any copies. This behavior should be changed such that mutation of the cached value is either safe or impossible.

@pmli, please have a look if you like my changes.

### CODE REVIEW

**Comment by pmli** [comment]
@sdrave I like your changes very much! (Maybe I will now try to understand caching :smiley:)

I've made some minor corrections and added `'Hinf_fpeak'` name in the `norm` method (this seems a bit nicer to me than adding another parameter).

**Comment by sdrave** [comment]
I agree with your change regarding `fpeak`. Only made a small change to ensure that the real computation cannot happen twice.

Shall  we merge this, or would you like more time for testing?

**Comment by pmli** [comment]
Caching didn't seem to work, so I've changed `cache_region=None` to `cache_region='memory'` in all system classes. Now it seems to work, which makes me happy.

You can merge now, I think.

**Comment by sdrave** [comment]
Oh, forgot that. Calling `enable_caching` with `None` as cache region will disable caching ...

**Pull request merged**
