### PR TITLE
Retire René as main developer

### PR DESCRIPTION
**Pull request by sdrave**

### CODE REVIEW

**Review by HenKlei — APPROVED** [review]

**Comment by renefritze** [comment]
Looks like I still have admin access to this repo @pymor/main, maybe through the org?

**Review by renefritze — APPROVED** [review]

**Comment by sdrave** [comment]
> Looks like I still have admin access to this repo @pymor/main, maybe through the org?

As a @pymor/contributors you have 'write' access meaning:

> Can read, clone, and push to this repository. Can also manage issues and pull requests

However, you should not be able to merge this PR or delete the repo. Are you?

**Comment by renefritze** [comment]
I can access the settings page for the repo, click delete everything even :smiling_imp: 
I can also "merge when ready"

**Comment by renefritze** [comment]
I'm still an owner: https://github.com/orgs/pymor/people?query=role%3Aowner
I cannot make myself just a member. But since I could make any other owner a member I'd say it's just a matter of one the other owner switching my role there.

**Comment by sdrave** [comment]
Thanks for the feedback @renefritze. Made you now a non-owner of the organization. Privileges gone?

**Comment by renefritze** [comment]
Yepp, looks good @sdrave :+1:

**Pull request merged**
