### PR TITLE
Fix `return_fpeak` handling in `pymor.models.iosys`

### PR DESCRIPTION
**Pull request by peoe**
This is a proposed fix to issue #2133.

### CODE REVIEW

**Review by pmli — COMMENTED** [review]
Thanks!
Would you also add tests? This method seems to be causing many issues.

**Comment by peoe** [comment]
I added a simple test in `pymortests/models/iosys_norm.py`. If you have more ideas what to test for or where to place this file, please let me know!

**Review by pmli — COMMENTED** [review]
Looks good. The new test file should include the copyright header and probably also the line `pytestmark = pytest.mark.builtin` as in [here](https://github.com/pymor/pymor/blob/141550bf7bf266185d501be5dce9f4ed9d309762/src/pymortests/models/iosys_add_sub_mul.py#L16) for the fenics test to pass.

**Review by pmli — APPROVED** [review]
Thanks!

**Pull request merged**
